### ISSUE TITLE
initialValues Display Incorrectly in Select Component with isSearchable Property

### ISSUE THREAD

**Issue by DavidResende0** [data-driven-forms/react-forms#1022]
**Description:** When trying to set the initialValues for a select component with the `isSearchable` property, the select treats the initialValues as the text to input into the field as opposed to the value of one of the options.

```
<FormRenderer
    schema={schema}
    initialValues={{ test: "test1" }}
    FormTemplate={FormTemplate}
    componentMapper={componentMapper}
    onSubmit={console.log}
/>
...
{
    component: "select",
    name: "test",
    id: "test",
    label: "Select",
    isSearchable: true,
    options: [
        {
          value: "test1",
          label: "This is test 1"
        },
        { value: "test2", label: "This is test 2" },
        { value: "test3", label: "This is test 3" },
        { value: "test4", label: "This is test 4" }
    ]
}
```

With `isSearchable`:
<img src="https://user-images.githubusercontent.com/64800041/113596324-28012300-9608-11eb-846a-065611577b40.png" width="300">

Without:
<img src="https://user-images.githubusercontent.com/64800041/113596634-9940d600-9608-11eb-9cdd-5b2aa6db9ebd.png" width="300">

**Example:** https://stackblitz.com/edit/mtevuf-byqvrw?file=schema.js

**Comment by rvsia** [comment]
There are some issues with using different components for each variant (`isSearchable` is using `ComboBox`, not `Select`, etc...). Unfortunately, `ComboBox` behaves differently than regular `Select`. 

You can workaround this by setting the whole value as the initial one until some fix is made:

```jsx
  initialValues={{
    test: {
      value: "test1",
      label: "This is test 1"
    }
  }}
```

**Comment by Hyperkid123** [comment]
Fix will be published soon. It will be also backported to v2 of the carbon mapper.

**Comment by Hyperkid123** [comment]
@DavidResende0 the issue is fixed also in version `@data-driven-forms/carbon-component-mapper@2.24.1` if you are stull on v2.
