### ISSUE TITLE
Missing tag control component in PF3 mapper

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#104]
As far as I see, the tag control component is just a dropdown with implicitly loaded data from a category (tag parent). The database-schema for the `DialogField` only stores the category, the actual data is being dynamically loaded upon when serializing the dialog. 

![Screenshot from 2019-09-05 10-05-16](https://user-images.githubusercontent.com/649130/64323384-b04eba80-cfc4-11e9-9725-de03f70cc504.png)

Maybe @romanblanco can tell more about it, but my idea would be to create simple a wrapper around the dropdown for compatibility.

**Comment by romanblanco** [comment]
From ManageIQ prespective, the difference between Tag Control field and Dropdown field is, as @skateman says, that the data [are loaded](https://github.com/ManageIQ/manageiq-ui-classic/blob/36522ada53a64a129cb3519b4183da8084dced1c/app/assets/javascripts/services/dialog_editor_http_service.js#L28-L33) implicitly from a `category` API.

Also there is no option to set Tag Control as multiselect, that we support in Dropdown field.

Comparing the Tag Control field to the other fields, Tag Control is also special by the fact it can't be set as Dynamic, nor it can have a `default_value` set.

**Comment by skateman** [comment]
@Hyperkid123 @rvsia my idea for a wrapper around dropdown still stands. Are you planning to support some kind of way to load data dynamically, e.g. by specifying a function in the schema? If yes, then this might be the first component to actually use it. Or if not, we can just preload the data into the schema when sending it from the server. Both solutions are acceptable for me.

**Comment by rvsia** [comment]
We actually has an option to load options when the select is mounted. However, it is in 'missing documentation' section. :crying_cat_face: 

Until it's done, you can look on an use case in MiQ: https://github.com/ManageIQ/manageiq-ui-classic/blob/a359b696b33f51e3c44a27050c34c9fee0ae9703/app/javascript/components/cloud-network-form/cloud-network-form.schema.js#L31

**Comment by Hyperkid123** [comment]
@skateman @romanblanco since async select is a thing already i think we should add this component type just as an alias in MIQ not here. The only issue is that now the the select accepts only a function but i would expect that you wanting to add some sort of url and have internal action to do the loading. We don't support that now but i have some ideas to enable this functionality.

**Comment by Hyperkid123** [comment]
@skateman can i close this issue? I want to remove tag control from the mapper since its is MIQ specific variant of async select.
