### ISSUE TITLE
Switch Component can't be set by initialValues

### ISSUE THREAD

**Issue by DavidResende0** [data-driven-forms/react-forms#1048]
**Description**: It's currently not possible to set the initialValues for a switch component. I'm not sure if this is intentional or a bug but I was wondering if this could be implemented

```
<FormRenderer
    schema={schema}
    initialValues={{ switchTest: true }}
    FormTemplate={FormTemplate}
    componentMapper={componentMapper}
    onSubmit={console.log}
/>
...
{
    component: "switch",
    id: "switchTest",
    name: "switchTest",
    label: "Switch",
    onText: "True",
    offText: "False"
}
```
<img src="https://user-images.githubusercontent.com/64800041/117356763-1ec2da80-ae82-11eb-8b3b-1ff85cd0c30c.png" width="150"> 

**Schema**: https://stackblitz.com/edit/switch-initalvalue?file=index.js

**Comment by rvsia** [comment]
Oh, I see, we are missing `defaultToggled` [attribute](https://react.carbondesignsystem.com/?path=/docs/components-toggle--default)

**Comment by rvsia** [comment]
Backported in `@data-driven-forms/carbon-component-mapper@2.24.4`
