### ISSUE TITLE
Multiselect Tool Issues

### ISSUE THREAD

**Issue by GilbertCherrie** [data-driven-forms/react-forms#1080]
First Issue: When using the isMulti: true for a select component a bug exists when trying to have preselected boxes. The bug arises when trying to preselect options based on an integer array and the option with value 0 is not included in the array. Below is a link to an example that better demonstrates and recreates the issue. When 0 is included in the array the correct options are preselected. When 0 is not in the array then only the first option in the array is selected and the rest of the array is ignored.

https://codesandbox.io/s/modal-multiselect-forked-7235o?file=/src/schema.js

Second Issue: Another question about the isMulti: true for the select component is how can I overwrite the default alphabetical sorting. In Carbon there is sortItems property that can be used to sort based on a custom function. Does the DDF schema have any way of achieving the same result of custom sorting.

**Comment by rvsia** [comment]
@GilbertCherrie Hello,

ad 2) you can add sortItems property to the schema. It works the same as the original prop.

**Comment by rvsia** [comment]
The fix for the first issue was released in the latest version and backported to [2.24.7](https://www.npmjs.com/package/@data-driven-forms/carbon-component-mapper/v/2.24.7). Please feel free to reopen, if there are any additional issues.
