### ISSUE TITLE
Field Array Component not Displaying initialValues until Add Button is Pressed

### ISSUE THREAD

**Issue by DavidResende0** [data-driven-forms/react-forms#1087]
**Description**:  When creating a field-array, any initialValues passed to components within the field-array remain hidden from view until the add button is pressed.
```
<FormRenderer
    schema={schema}
    initialValues={{
    fieldArray: { text: 'this is a test', select: 'test2' }
    }}
    FormTemplate={FormTemplate}
    componentMapper={componentMapper}
    onSubmit={console.log}
/>
```
**Before**
<img src="https://user-images.githubusercontent.com/64800041/122271719-b833d200-cead-11eb-91d4-a6d2fc497655.png" width="300">
**After Add Button is Clicked**
<img src="https://user-images.githubusercontent.com/64800041/122271740-c08c0d00-cead-11eb-8283-32376bed5c1a.png" width="300">

**Schema**: https://stackblitz.com/edit/field-array-test?file=schema.js

**Comment by rvsia** [comment]
Hello, the value of the field array has to be an array:

```jsx
initialValues={{
    fieldArray: [{ text: 'this is a test', select: 'test2' }]
    }}
```

**Comment by DavidResende0** [comment]
Oh my bad, that was the issue. Thanks @rvsia.
