### ISSUE TITLE
Inconsistent behavior between SELECT and RADIO components in PF3

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#110]
The `SELECT` component can live without an `options` array, however, the `RADIO` throws an *Cannot read property 'map' of undefined* error. There's no behavioral difference between a single-select dropdon and a radio, therefore, I think they should behave consistently when (not) getting the same input.

**Comment by Hyperkid123** [comment]
A suspect that chekcbox might do the same

**Comment by skateman** [comment]
@Hyperkid123 nope, checkbox works well without it

**Comment by rvsia** [comment]
Closed by https://github.com/data-driven-forms/react-forms/pull/114
