### ISSUE TITLE
Console Warnings for Empty Text-Field Label

### ISSUE THREAD

**Issue by GilbertCherrie** [data-driven-forms/react-forms#1102]
When trying to create a hidden text field with an empty label it results in console warnings.

Error:
Warning: Failed prop type: The prop `labelText` is marked as required in `ForwardRef(TextInput)`, but its value is `undefined`.

Example Schema:

export default {
  "fields": [
    {
      "component": "text-field",
      "type": "hidden",
      "label": "",
      "name": "first-name"
    }
  ]
};

Stack Blitz Example:

https://stackblitz.com/edit/g684qh?file=schema.js

**Comment by rvsia** [comment]
Hello,

Carbon’s `TextInput` requires the labelText as you can see [here](https://react.carbondesignsystem.com/?path=/docs/components-textinput--default). So it’s not something that DDF can fix. I recommend to implement a custom input element for hidden fields + use `hideField` prop to hide the field in DOM.

**Comment by kavyanekkalapu** [comment]
@rvsia Right now is just adding type: hide only in input field, is it possible to add same for label too?

**Comment by rvsia** [comment]
@GilbertCherrie You can also “hack” this by setting `labelText: “”` https://stackblitz.com/edit/g684qh-ety2gw?file=schema.js labelText is computed from label in DDF to achieve a consistency across all mappers, and when it’s empty, it’s not used.

@kavyanekkalapu yeah, there is hideField that hides the whole element in DOM https://data-driven-forms.org/schema/introduction#heading-hidefield

**Comment by GilbertCherrie** [comment]
@rvsia Thanks so much for your help using hideField fixed the issue
