### ISSUE TITLE
Form Renderer - Custom Implementation - Date Picker and Date object Issue

### ISSUE THREAD

**Issue by jessieweiyi** [data-driven-forms/react-forms#1109]
**Scope**: <DESCRIBE SCOPE OF THIS ISSUE, i.e.: PF4 mapper, Form renderer>

Form renderer

**Description**

I am having a custom implementation of Form Renderer. I bumped into a weird issue related to the Date Picker and Date object. Hope someone here can shed some light on what is causing the issue. 

Basically, the Date Picker is expecting or outputting a Date object as value. 

If initialValue is NOT provided, everything works fine and user can set the value or change the value using the Date Picker. If initialValue is provided and users do not touch the input, it is also ok. However, if users touch the input, the underlying value becomes **undefined**.  

An example is available at:
https://codesandbox.io/s/eager-meadow-qli49?file=/src/DateComponent.tsx:227-684

<img width="537" alt="Screen Shot 2021-08-19 at 9 19 11 PM" src="https://user-images.githubusercontent.com/5362048/130060074-59230b3b-4c25-46c6-a4ad-2a69c1c95cd4.png">

I have added some debug information in the source. I can confirm that the DatePicker onChange event is triggered in all the cases. But the value just disappear when the initialvalue is provided and users change the input. 

This is the output of getState().values when the form is rendered. 

<img width="730" alt="Screen Shot 2021-08-19 at 9 32 14 PM" src="https://user-images.githubusercontent.com/5362048/130061620-c3621ef7-ebd0-4571-9ec7-a8597510c776.png">

This is the output of getState().values when users select a date from DatePicker. 

<img width="482" alt="Screen Shot 2021-08-19 at 9 32 27 PM" src="https://user-images.githubusercontent.com/5362048/130061608-c9c11f73-310d-4c35-ab76-6d124f32de3a.png">

This is the output in the onChange handler of the DatePicker. 

<img width="901" alt="Screen Shot 2021-08-19 at 9 34 49 PM" src="https://user-images.githubusercontent.com/5362048/130061891-278be55a-7e4a-48b0-9818-765f33e920da.png">

**Schema**

const schema = {
  fields: [
    {
      component: componentTypes.DATE_PICKER,
      name: "date1",
      label: "Date 1",
      validate: [
        {
          type: validatorTypes.REQUIRED
        }
      ]
    },
    {
      component: componentTypes.DATE_PICKER,
      name: "date2",
      label: "Date 2",
      validate: [
        {
          type: validatorTypes.REQUIRED
        }
      ]
    }
  ]
};

const initialValue = {
  date1: new Date()
};

<If it's possible, please provide a schema which reproduces the issue>

**Comment by Hyperkid123** [comment]
Hi @jessieweiyi. I feel like the form is unable to parse the onChange value so it falls back to undefined. I am currently on vacation until the end od the week. @rvsia could you please take a closer look?

**Comment by rvsia** [comment]
I found the same behavior with our Blueprint `DatePicker` as well.  🤔  I will investigate once I have free time.
