### ISSUE TITLE
Add "Description" to PF4 Select

### ISSUE THREAD

**Issue by ddonahue007** [data-driven-forms/react-forms#1113]
**Scope**: <DESCRIBE SCOPE OF THIS ISSUE, i.e.: PF4 mapper, Form renderer>
PF4 mapper

**Description**
There is a need to add the Description field to the PF4 Select structure in DDF as this should give us the functionality of the Patternfly Drop down component with descriptions 
https://www.patternfly.org/v4/components/dropdown#dropdown-with-descriptions

![Screen Shot 2021-08-30 at 11 11 42 AM](https://user-images.githubusercontent.com/57504257/131361719-933acd06-0703-40dc-8f28-218d1cdd067d.png)

**Schema**

<If it's possible, please provide a schema which reproduces the issue>

**Comment by Hyperkid123** [comment]
@ddonahue007 We will add a `description` attribute to the option object.
