### ISSUE TITLE
Inconsistent select width compared to other components in PF3

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#113]
The width of the select fields isn't 100% unlike all other components. This might be intentional, but it's a little weird ...

![Screenshot from 2019-09-06 13-24-14](https://user-images.githubusercontent.com/649130/64424543-b2d71000-d0a9-11e9-9ec7-f59d445a5fa9.png)

**Comment by Hyperkid123** [comment]
@skateman that is by PF design. Originally it was 100%. Can't do anything about this :disappointed:
