### ISSUE TITLE
Feature: Option Groups within PF4 Select Component

### ISSUE THREAD

**Issue by steverhoades** [data-driven-forms/react-forms#1145]
**Scope**: PF4 mapper

**Description**
Currently within the Select component it does not appear possible to create option groups. There is support for the [Select component within PF4 along with Groups](https://www.patternfly.org/v4/components/select) however. It would be great to be able to provide a schema like the one below to support this feature.

![image](https://user-images.githubusercontent.com/1146668/137150330-0b03bba8-b1fd-4062-9254-f3ac3593ff9a.png)
 

**Proposed Schema**
```
const schema = {
    fields: [
        {
          "component": "select",
          "label": "Select Option",
          "name": "Option",
          "simpleValue": true,
          "isGroup": true,
          "options": [{
             group: "Lots of Placeholders",
             options: [
                {
                  "label": "Placeholder1",
                  "value": "Placeholder1"
                },
                {
                  "label": "Placeholder2",
                  "value": "Placeholder2"
                },
            ]
          }]
        }
    ]
};
```

**Comment by Hyperkid123** [comment]
Yup, we are missing that one.
