### ISSUE TITLE
Ability to set the number of rows for TEXTAREA_FIELD

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#115]
As the [example is not available](https://data-driven-forms.org/component-example/text-area), I am not sure if this is possible or not. But I'd like to have an option for textareas to optionally set the number of rows for them.

**Comment by rvsia** [comment]
The example is here https://data-driven-forms.org/component-example/textarea-field, however you won't find this specific prop there. Data Driven Forms components are designed to pass all additional unspecific props in the schema to the component, so you can provide a [html attribute row](https://www.w3schools.com/tags/tag_textarea.asp) to the textarea in the schema.

```jsx
const schema = {
  fields: [
    {
      component: componentTypes.TEXTAREA,
      name: "name",
      label: "Your name",
      rows: 10
    }
  ]
};
```

**Comment by skateman** [comment]
Thanks!
