### ISSUE TITLE
mui-component-mapper: Could not find module in path: '@mui/material/styled' [...] esm/dual-list-select/dual-list-select.js

### ISSUE THREAD

**Issue by 1dl3** [data-driven-forms/react-forms#1168]
**Scope**: Material UI Component Mapper (Beta MUI migration)

**Description**:
I'm trying to use the material-ui mapper migration  "@data-driven-forms/mui-component-mapper": "3.16.0-v5-beta" however I'm running into this issue. Am I missing something stupidly obvious ?

[Codesandbox Sample](https://codesandbox.io/s/gracious-hellman-uosvb?file=/package.json:191-250)

**Comment by Hyperkid123** [comment]
@rvsia i think its possible caused by the transform import paths. The module `'@mui/material/styled'` truly does not exist. We may have to exclude the `@mui/material` from the transformation.

**Comment by Hyperkid123** [comment]
@rvsia this could fix it. Can you try it out?

```diff
diff --git a/packages/mui-component-mapper/src/dual-list-select/dual-list-select.js b/packages/mui-component-mapper/src/dual-list-select/dual-list-select.js
index 732516d9..b9f63b7c 100644
--- a/packages/mui-component-mapper/src/dual-list-select/dual-list-select.js
+++ b/packages/mui-component-mapper/src/dual-list-select/dual-list-select.js
@@ -1,5 +1,5 @@
 import React from 'react';
-import { styled } from '@mui/material';
+import { styled } from '@mui/material/styles';
 import PropTypes from 'prop-types';
 import clsx from 'clsx';

```

**Comment by rvsia** [comment]
@Hyperkid123 Yeah, this is definitely it!

**Comment by rvsia** [comment]
I will prepare a fix and new version.

**Comment by rvsia** [comment]
Fix released in `3.16.0-v5-beta-1`, the example now works.

**Comment by rvsia** [comment]
@1dl3 Thank you so much for reporting this!

**Comment by 1dl3** [comment]
oh wow thanks guys that was really fast!
