### ISSUE TITLE
Docs inconsistencies

### ISSUE THREAD

**Issue by Hyperkid123** [data-driven-forms/react-forms#117]
If you find any bugs, strange texts or any other issues in docs, please post them to this issue. It will be pinned for very very long time.

**Comment by skateman** [comment]
![Screenshot from 2019-09-11 09-46-46](https://user-images.githubusercontent.com/649130/64678045-16ca5180-d479-11e9-91b4-4df0c98162c4.png)

title and description inconsistent

**Comment by skateman** [comment]
![Screenshot from 2019-09-11 09-47-22](https://user-images.githubusercontent.com/649130/64678079-2ba6e500-d479-11e9-944e-8a38665847fe.png)

you're mentioning the *data driven forms repository* but there is no such thing

**Comment by skateman** [comment]
`buttonsLabels` prop should be `buttonLabels` and its documented default values are not working:
![Screenshot from 2019-09-13 13-11-08](https://user-images.githubusercontent.com/649130/64858570-086e6800-d628-11e9-8ca3-2be95b2ec210.png)

It actually accepts `submitLabel` and `cancelLabel`...

**Comment by skateman** [comment]
Broken link to the [list of standard components](https://data-driven-forms.org/renderer/form-schemas) on [this](https://data-driven-forms.org/renderer/field-provider) page

**Comment by skateman** [comment]
There's no mention of the `initialValue` of each component, only the global `initialValues`.

**Comment by Hyperkid123** [comment]
> Broken link to the [list of standard components](https://data-driven-forms.org/renderer/form-schemas) on [this](https://data-driven-forms.org/renderer/field-provider) page

@skateman should be fixed by https://github.com/data-driven-forms/react-forms/issues/137

**Comment by Hyperkid123** [comment]
> There's no mention of the `initialValue` of each component, only the global `initialValues`.

@skateman should be fixed by https://github.com/data-driven-forms/react-forms/issues/138
