### ISSUE TITLE
When use dataType=dataTypes.NUMBER, the validation should allow negative number

### ISSUE THREAD

**Issue by jessieweiyi** [data-driven-forms/react-forms#1256]
**Scope**: <DESCRIBE SCOPE OF THIS ISSUE, i.e.: PF4 mapper, Form renderer>

**Description**

When setting dataType=dataTypes.NUMBER and the number users type is negative, the form shows error. I can reproduce on this page: https://data-driven-forms.org/schema/data-types.

![Screen Shot 2022-05-18 at 10 25 38 PM](https://user-images.githubusercontent.com/5362048/169038769-d005bfbb-2000-4451-8af7-dd7ca019bff7.png)

**Schema**

```
{
      fields: [
        {
          name: "coordinates.lat",
          label: "Latitude",
          component: componentTypes.TEXT_FIELD,
          type: "number",
          dataType: dataTypes.NUMBER,
          validate: [
            {
              type: validatorTypes.REQUIRED,
            },
          ],
        },
        {
          name: "coordinates.lon",
          label: "Longitude",
          component: componentTypes.TEXT_FIELD,
          type: "number",
          dataType: dataTypes.NUMBER,
          validate: [
            {
              type: validatorTypes.REQUIRED,
            },
          ],
        },
      ],
    };
```

<If it's possible, please provide a schema which reproduces the issue>

**Comment by rvsia** [comment]
@jessieweiyi Good catch, thanks! A fix is here: https://github.com/data-driven-forms/react-forms/pull/1257
