### ISSUE TITLE
Existence of invisible fields

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#128]
Is there a way to simply control the visibility (true/false) of a form item through the schema? I haven't found anything in the docs about it.

**Comment by Hyperkid123** [comment]
You can use input type hidden (text_field)

**Comment by skateman** [comment]
Yeah, but what about other fields? Miq dialog schema has a display property

**Comment by Hyperkid123** [comment]
How exactly does it work? We have conditional fields which show/hide based on some condition. Or do you just want a prop on any component which would remove it from a DOM?

**Comment by skateman** [comment]
@hyperkid123 if the condition can be a boolean, then it might work, about the other part, I'll have to take a deeper look into the miq dialogs. Will get back to you...

**Comment by Hyperkid123** [comment]
@skateman it can be any value you want

**Comment by skateman** [comment]
@Hyperkid123 the dialog itself is in the DOM, but it is not visible. Probably some kind of automate magic can make it visible in some cases.

**Comment by skateman** [comment]
The [condition](https://data-driven-forms.org/renderer/condition) would be a little hacky for this and AFAIK passing functions into the schema is something we don't want...so I'm a little lost :confused:

**Comment by Hyperkid123** [comment]
@skateman can you post an example of such condition? Maybe we can find some pattern in it.

**Comment by skateman** [comment]
@Hyperkid123 the `condition` is a no go for me, because it's not adding the form element to the DOM. I need a `display: none` kind of solution here.

**Comment by Hyperkid123** [comment]
OK, that is something we can add.

**Comment by Hyperkid123** [comment]
@skateman ok I've started working on this there is one thing and that is the prop name. Easiest way would be wrapping the hidden element in div with
```html
<div hidden>...</div>
```
The question is how to call it because word `hidden` is very common prop name and since it has to be extracted and not passed to final component from same as condition or validate is now, it might cause some issue with certain design systems.

is something like `hideField: true` in schema OK?

**Comment by skateman** [comment]
What about `display: false`?

**Comment by Hyperkid123** [comment]
`display`, `hidden` etc are common props for number of react components across multiple libraries :( I don't want to make them map these props to something else.

**Comment by skateman** [comment]
As far as I see, the wrapper is above the mapped component, therefore, there's no way to override the visibility using a custom component mapper. My goal is to not have the items hidden in the editor (i.e. custom mapper), but only when rendering the form for "playing" it. @Hyperkid123

**Comment by rvsia** [comment]
So, just remove the `hideField` from the editor schema.

**Comment by skateman** [comment]
@rvsia the schema is the same and should be the same, the rendering should be different. If I start conditionally altering the schema, I'll end up with :spaghetti: all over the place.

Also if we're here, I don't really understand why you could not chose `hidden` if you're using a wrapper that is around the mapped component, therefore, there's an ability to not pass the data further. The two things together don't make sense :confused:

**Comment by rvsia** [comment]
I'm not sure if I understand that correctly. What do you mean by different rendering? DDF has always the same rendering, only schemas are different. And about editor, I think you should do some pre-processing of the schema, flag the hidden ones and change the schema again when converting it out of the editor.

**Comment by skateman** [comment]
@rvsia this is a crazy antipattern, and just to compensate a useless feature. I'd rather implement my own `hideField` implementation inside the custom component mapping. In this case, you can just simply revert the feature.

**Comment by skateman** [comment]
Yeah, you will have to revert the feature as now the `hideField` prop isn't even bubbling down to the component level :disappointed:

**Comment by skateman** [comment]
@Hyperkid123 @rvsia can you please revert this feature? It's totally useless as it is implemented right now.

**Comment by Hyperkid123** [comment]
@skateman so you want us to duplicate the same code across all the mappers instead of doing it one place? I think we should sit down and talk about how we are doing things here.

It might be "useless" for your use case but your use case is something completely different than for what is this library being used for and was designed for.

**Comment by skateman** [comment]
@Hyperkid123 I agree that we should sit down, because the PR and the issue have been merged/closed before I could take a look.

**Comment by rvsia** [comment]
Actually, I found this very useful in Sources-UI, it prevents rendering empty whitespaces in forms, where `type: hidden` is used (obtained by DB).
