### ISSUE TITLE
Common select fails without onInputChange

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#1287]
**Scope**: Common select (possibly MUI)

**Description**

Working on [cascading select](https://github.com/data-driven-forms/react-forms/pull/1285) I found that the select fails when `noInputChange` is provided - but it should not be required.

**Steps to reproduce**

1. remove `onInputChange: () => null,` from the example
2. select favorite category
3. select food
4. change the category

```jsx
select.js:160 Uncaught TypeError: _onInputChange is not a function
    at onInputChange (select.js:160:14)
```

![Screenshot 2022-07-11 at 16 04 28](https://user-images.githubusercontent.com/32869456/178282849-d7498f19-ffe5-40b8-be61-a93a49486078.png)

**Comment by AhmedMustafa2201** [comment]
https://data-driven-forms.org/examples/cascading-select
@rvsia I'm not sure if this issue still exists or not. because I've tried it and it seems working

**Comment by AhmedMustafa2201** [comment]
@rvsia I don't think it's still an issue. because i've tried to reproduce the issue and didn't appear the error anymore

![image](https://github.com/data-driven-forms/react-forms/assets/59970699/660e585a-7d7c-4690-a031-739c834d25eb)

I think it's resolved, right?

**Comment by rvsia** [comment]
@AhmedMustafa2201 Yep, I checked it again and it seems it was resolved. Thank you for checking this! 👍
