### ISSUE TITLE
Upgrading to carbon-components-react 7.56 causing components to break

### ISSUE THREAD

**Issue by GilbertCherrie** [data-driven-forms/react-forms#1298]
After upgrading to carbon-components-react 7.56 I ran into this bug with the Carbon DDF dual list select component.
```

Uncaught (in promise) Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Check the render method of DualListSelectInner
```

Not sure if this affects other components but this is the only one I found.

**Comment by Hyperkid123** [comment]
I am looking at the docs and we are basically dealing with a slightly botched major realse.

There is a new package called `@carbon/react` that replaces the `carbon-components-react`. But there is also a new major release of `carbon-components-react` v 8. But also some breaking changes (import changes) made it into a minor release of the `carbon-components-react`.

So the path that we will probably follow is this:

Fix the imports for the versions `^7.56.0` and `^8.0.0` in a patch release. And then prepare migration to the new package `@carbon/react` and do a new minor release for the mapper as we do want to support the LTS carbon release.
