### ISSUE TITLE
Allow hideField property to be updated using resolve props.

### ISSUE THREAD

**Issue by Rishi74744** [data-driven-forms/react-forms#1309]
Currently hideField value for a component can be updated using resolve props. But there are scenarios where this is required e.g - updating the visibility of field based on results of an API after submit is called. Thus, it should be allowed to update the hideField using resolveProps.

Creating this issue after discussion with @Hyperkid123

**Comment by rvsia** [comment]
As `hideField` is just `<div hidden={true | false} ...>` and this is done before `resolveProps` are actually resolved I would recommend to use a slightly different approach. (And additionally, `resolveProps` works only for form state connected fields so we would have to change a lot to support this behavior.)

1) Use custom CSS (`display: none;`)
2) Try to pass `hidden: true` to your component root element from the schema

**Comment by Hyperkid123** [comment]
Yeah, I am torn between the two. The original use case was different than in the described scenario. @Rishi74744 as discussed is it possible to use the `hidden` prop directly in the element? What component mapper do you use? I think the same can be achieved without changing the internal logic of the `hideField` attribute.

**Comment by Rishi74744** [comment]
Hi @Hyperkid123,
I have used hidden prop directly. I am using mui mapper. I was able to achieve the desired result.

**Comment by rvsia** [comment]
@Rishi74744 So I am closing this issue, feel free to reopen in case of any other issues. ☺️
