### ISSUE TITLE
The initialValue props are not being updated upon schema change

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#133]
Whenever you edit the `initialValue` of a field, it's not getting updated even though the component is re-rendered. @rvsia told me that this has something to do with the state of the given component. 

I have no way to force a new initial state with anything else than a complete re-render of the whole `FormRender` component. This is a UX disaster as the re-render makes the page flashy upon every drag&drop operation.

**Comment by skateman** [comment]
Same happens for `options` in select and my guess is that elsewhere as well :disappointed:

**Comment by Hyperkid123** [comment]
There is a way to re-initialze the form state. The field gets a prop `formOptions.initialize` which is documentend here: https://final-form.org/docs/final-form/types/FormApi#initialize

this is only accessible by form components not form outside! We could technically expose the form api in a callback like `formDidMount` which could send all these options outside of the form but i want to avoid it unless its something that is desperately needed for some reason.

**Comment by skateman** [comment]
Yeah, I'm editing a form and passing a brand new schema (immutable solution as you asked for) and the default values don't update. Also when adding new options to the dropdown, the options don't show up. 

I'm not entirely sure if the whole form should be reinitialized, I just need the changed schema to prevail in the form consistently all the time.

**Comment by Hyperkid123** [comment]
The issue is that initial values are after component mount added to form state values which is then preserver and the state has higher priority than the initialValues which will keep the first value in. If you want to change the initial values you unfortunatelly have to initialize the form. Or you might try to use `defaultValue` prop instead of the `initialValue` on the field.

**Comment by Hyperkid123** [comment]
Options are not stored in state i have to investigate why its not being updated.

**Comment by skateman** [comment]
Seems that the `defaultValue` behaves the same way :disappointed:

**Comment by Hyperkid123** [comment]
Ok let me try adding some didMount callback which would expose the formAPI and re-initialize the form.

**Comment by Hyperkid123** [comment]
@rvsia this is an issue with select. Take a look once you have time

**Comment by skateman** [comment]
fixed here https://github.com/skateman/ddf-editor/commit/c69263cf496899290449410f3bb9f3ab580eb5e2
