### ISSUE TITLE
Question: Accepting user input for a field which is controlled conditionally

### ISSUE THREAD

**Issue by imabp** [data-driven-forms/react-forms#1349]
**Scope**: Conditoins inside form

**Description**
So I have two toggle switches, `hidden` and `filterable`.
I want the filterable to be controlled by hidden, but also accept the user input.
For example

If a user turns hidden toggle to true, the filter toggle should turn to false, but a user can toggle the filter toggle back to true, by toggling the filter toggle, without affecting the hidden toggle state.

I have tried, experimenting with resolveProps and condition object, but it makes filter toggle to a fixed state, and user cannot change it. And also, on re-mounting of the component if hidden and filter both are true, the filter automatically changes to false (while using condition).

**Comment by Hyperkid123** [comment]
Hello @imabp. If I understand your question correctly, I think you are looking for a [set condition](https://data-driven-forms.org/schema/condition-set).

Here is an example: https://codesandbox.io/s/epic-fog-ds571m?file=/src/App.js

The schema can look something like this
```js
const schema = {
  fields: [
    {
      component: "switch",
      name: "hidden-toggle",
      label: "Hidden"
    },
    {
      component: "switch",
      name: "filterable-toggle",
      label: "Filterable",
      condition: {
        when: "hidden-toggle",
        is: true,
        then: {
          set: {
            "filterable-toggle": false
          }
        },
        else: {
          visible: true
        }
      }
    }
  ]
};
```

**Comment by imabp** [comment]
@Hyperkid123 thankyou for the efforts..
I have tried something similar and also reproduced the above issue in above codesandboox link 

the above code doesn't work when you have filter toggle as true manually, and hidden as true, and when you toggle back the hidden to false and then true, the filter toggle doesn't toggles back to false, and the whole code then fails to have the expected behavior.

**Comment by Hyperkid123** [comment]
OK, I think I understand a bit more now.

> If a user then changes the toggle, any future set condition trigger will not change the value.

That is an expected default behavior and the setter was intentionally designed this way. If you want to re-trigger the setter, you have to reset the setter value. And you can do that in the else branch. By adding an empty `set` object.

```js
else: {
  visible: true,
  set: {}
}
```

I have updated the codesandbox. Let me know if that is the required behavior.

```js
const schema = {
  fields: [
    {
      component: "switch",
      name: "hidden-toggle",
      label: "Hidden"
    },
    {
      component: "switch",
      name: "filterable-toggle",
      label: "Filterable",
      initialValue: true,
      condition: {
        when: "hidden-toggle",
        is: true,
        then: {
          set: {
            "filterable-toggle": false
          }
        },
        else: {
          visible: true,
          set: {}
        }
      }
    }
  ]
};
```

**Comment by imabp** [comment]
@Hyperkid123 still it doesn't work for this case.

When filter toggle false and hidden is true,
And if you toggle hidden to false, the filter should automatically then turn to true.

In a short way, hidden can control the state of filter.
But usse can also freely choose the filter state, irrespective of hidden condition.

**Comment by Hyperkid123** [comment]
OK I have updated the example again. It seems like you require the opposite value of the hidden value. If that does not help, then I think you might need a custom component as the dependency is probably too strict for a condition setter.

```js
condition: {
  when: "hidden-toggle",
  is: true,
  then: {
    set: {
      "filterable-toggle": false
    }
  },
  else: {
    visible: true,
    set: {
      "filterable-toggle": true
    }
  }
}
```

**Comment by imabp** [comment]
Thanks @Hyperkid123 
I was trying this with my complex component.
Which has these two toggles in a different Accordion component.

Problem I face with re-rendering, is switching the hidden toggle, even if, the filter is not rendered, and I think, keeping these toggles inside the same accordion, can help me solve that issue.

Thank you again.

Can you tell me, how `initialValue` works in DDF? I am using this toggle with the `initialValue: true`   I see, during the mount, form.getState() has `initialValues` object as `undefined`.  But on re-render of the form, the `initialValues` object is populated with the schema definition.

**Comment by Hyperkid123** [comment]
there are two ways of defining the field initial value

1. via "global object" prop on the renderer
2. directly on the field in the schema

If you are using the `initialValue` on a field, it will not be present in the form until the component is first rendered. And the state manager is rendered before its children. Field registration happens at runtime so there can be a short initialization period of time where the global state and local field state might be out of sync.

This starts to make sense when you introduce conditional fields.

Imagine a scenario where field `A` is rendered only after a certain form field has some value. You wait for it to have `initialValue` "Foo". If you would define that value in the global `initialValues` object, that value would be present in the form state from the start. And if you would submit the form, even without the field `A` ever appearing in the UI, it would still show the "Foo" string in the submitted values object.

So then you want to use the local field `initialValue` prop. But we can only set the local value during the component mount.

That's a rough explanation of how the prop works.

**Comment by imabp** [comment]
Thank you @Hyperkid123, for this bird eye view on the state manager and global initialisation.

For my case, I think, it will be more suitable to use the global initialisation for these toggles.

Thanks once again for the efforts. 
If you have a buy me a coffee would like to buy you a one for your efforts on this discussion .


Also you can mark this as answered label.

**Comment by Hyperkid123** [comment]
I don't have a "buy me a coffee" but thank you anyway :slightly_smiling_face:
