### ISSUE TITLE
Handling onChange events

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#135]
Would it be possible to call an `onChange` function any time an item has been changed?

**Comment by Hyperkid123** [comment]
I don;t get that. You want to add custom `onChange` function?

**Comment by skateman** [comment]
I'll look into this, thanks

**Comment by Hyperkid123** [comment]
@skateman any update?

**Comment by skateman** [comment]
@Hyperkid123 I'll probably not need it, investigating right now.
