### ISSUE TITLE
Unable to retrieve a component in ddf through testing-library's *ByLabelText

### ISSUE THREAD

**Issue by xPhentom** [data-driven-forms/react-forms#1353]
**Scope**: Ant design mapper 

**Description**
Testing-library has the ability to let a tester retrieve the component associated to a label by using the label text: https://testing-library.com/docs/queries/bylabeltext/

With our custom components we were able to pass the name from the field to the Ant design label (using the 'for' property) and the matching component (using the 'id' property).
However, the default components generated by DDF does not have this ability.

**Schema**
Here's the playground example. It's mainly to show the code since you can't run the tests properly on codesandbox.
https://codesandbox.io/s/data-driven-forms-forked-9wq2v1?file=/src/test.spec.jsx

**Comment by rvsia** [comment]
Hello, thanks for reporting it.

yeah, we need to put the name there. I will prepare a PR.

You can also use a workaround:

```jsx
          {
            component: 'text-field',
            name: 'abc',
            label: 'Some label text',
            FormItemProps: {
              htmlFor: 'abc',
            },
          },
```
