### ISSUE TITLE
InitialValues are inconsistent

### ISSUE THREAD

**Issue by stijnvanhulle** [data-driven-forms/react-forms#1356]
There has been a fixed done based on this issue: https://github.com/data-driven-forms/react-forms/issues/1353 but when we update to the latest version of Data-Driven we have issues that the initialValues will not work like it used to.

**Name** has been added to the FormItem component(as a prop) but that is creating some inconsistent behaviours. When doing some research on what name is doing in ant-design I found the following thing:

> Ant-Design uses name inside of Form.Item to determine the key to save the formValue. When name is set it will also use the FormContext of ant-design to resolve the value instead of using the props value and defaultValue. This means setting the name will be handled differently causing it to not always get the correct value. https://4x.ant.design/components/form/#API
![afbeelding](https://user-images.githubusercontent.com/5904681/212866716-402cf1bd-faef-42b2-b280-43ea19c289bb.png)

Examples:

- Codesandbox with version 3.19.0 (before the use of name): https://codesandbox.io/s/data-driven-forms-initialvalues-3-19-0-ektnze?file=/demo.tsx
- Codesandbox with version 3.19.1 (before the use of name): https://codesandbox.io/s/data-driven-forms-initialvalues-3-19-1-h1jdqc
 
Will it be possible to remove the name(we will lose then the use of **getByPlaceholder**) but this will resolve the issues we have today. Maybe there is another solution with using name that will not impact the initialValues but I have not yet found a solution for that.

Thanks
Stijn

**Comment by rvsia** [comment]
Great catch, this is the reason why we didn't add it there.. I have a possible fix, will open a PR asap.
