### ISSUE TITLE
Warning displayed when `is` property in a condition uses a custom function

### ISSUE THREAD

**Issue by edhollinghurst** [data-driven-forms/react-forms#1377]
**Description**
It appears that when a custom function is used for the `is` property in a condition, a warning is shown in the console.

``Warning: Failed prop type: Invalid prop `condition` supplied to `Memo`.``

<img width="1105" alt="SCR-20230425-jpuk" src="https://user-images.githubusercontent.com/2844785/234235798-6b26f00e-503b-4e4e-b8a1-eab6b9e872bb.png">

You can view the example at https://codesandbox.io/s/react-form-renderer-custom-function-condition-udj3sr

**Comment by rvsia** [comment]
Hello,

yes, good catch! We should add `function` here: https://github.com/data-driven-forms/react-forms/blob/50e054dfec6173d369031195a529e5d8b0b3101c/packages/react-form-renderer/src/condition/condition.js#L106

I can open a PR later

**Comment by edhollinghurst** [comment]
Thanks @rvsia !
