### ISSUE TITLE
Releases are blocking other results in Algolia

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#1392]
**Scope**: Documentation

**Description**

Releases are blocking other results in Algolia

![Snímek obrazovky 2023-06-30 v 10 08 24](https://github.com/data-driven-forms/react-forms/assets/32869456/b4b6d1c9-f3cf-4cff-be5c-bb0f83212bb1)

**Comment by Hyperkid123** [comment]
right, we should push the priority down on these.

**Comment by rvsia** [comment]
@Hyperkid123 yeah, now it works! :)
