### ISSUE TITLE
Internal links/buttons have wrong color

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#1393]
**Scope**: Documentation

**Description**

Buttons (internal links) have wrong color, should be the same as text

![Snímek obrazovky 2023-06-30 v 10 09 45](https://github.com/data-driven-forms/react-forms/assets/32869456/7e55f040-492c-4c22-8603-bcb08750787c)
![Snímek obrazovky 2023-06-30 v 10 09 31](https://github.com/data-driven-forms/react-forms/assets/32869456/fc7dcac3-b828-4858-8ea4-e0d26f604c0c)

**Comment by AhmedMustafa2201** [comment]
@rvsia could you please review my PR and assign this issue to me?
