### ISSUE TITLE
Anchor links do not copy the whole address

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#1395]
**Scope**: demo

**Description**

When you click on a chapter anchor button, only `pathname` is copied to the clipboard, the host and rest are missing.

![Snímek obrazovky 2023-07-03 v 9 24 24](https://github.com/data-driven-forms/react-forms/assets/32869456/3431f511-22c2-47e3-9a82-e8e58e38b63b)

Clipboard: `/introduction#comparisonwithotherformlibraries`

**Comment by abdul-o1** [comment]
could you describe the problem a bit in detail

**Comment by Hyperkid123** [comment]
@abdul-o1 We are missing the origin part of the URL.

So instead of `https://www.data-driven-forms.org/introduction#howtostart` only the pathname part is copied to clipboard: `/introduction#howtostart`

**Comment by AhmedMustafa2201** [comment]
@rvsia could you please review my PR?
