### ISSUE TITLE
Options with "value" field as object or array type are duplicated

### ISSUE THREAD

**Issue by gkarat** [data-driven-forms/react-forms#1401]
**Scope**: PF4 mapper, Form renderer

**Description**

How to reproduce: use a schema with `component` set to "select", and `isSearchable` to "true" with `loadOptions` function (so that you are able to asynchronously load values for the select component. Also, in `loadOptions` return a promise that resolves in an array with options. The options have to have value of array or object type, not primitive (like string or numbers).

Current behavior: the select component duplicates the value as you type in the select component and new data loads.

[Screencast from 2023-08-22 18-01-52.webm](https://github.com/data-driven-forms/react-forms/assets/31385370/b656cb15-7545-4aff-8903-a133e4abb60d)

Expected behavior: the select component renders just only the options it gets from `loadOptions`.

**Schema**

```
const loadOptions = (searchValue = '') => {
  return getGroups({ name: searchValue }).then((data) => {
    return data.results.map(({ name, id }) => ({
      label: name,
      value: { id, name },
    }));
  });
};

const exampleSchema = (hosts) => ({
  fields: [
    {
      component: 'select',
      name: 'group',
      label: 'Select a group',
      simpleValue: true,
      isSearchable: true, // enables typeahead
      isRequired: true,
      isClearable: true,
      placeholder: 'Type or click to select a group',
      loadOptions,
      options: [],
      validate: [{ type: validatorTypes.REQUIRED }],
    }
  ],
});
```

**Comment by Hyperkid123** [comment]
As the option value can be anything, we will have to provide an interface that will allow custom compare functions to support any shape of the option value.
