### ISSUE TITLE
For component type tabs, the actions props not working 

### ISSUE THREAD

**Issue by anjalikalsariya** [data-driven-forms/react-forms#1430]
Here is the schema: 

```
{
  "title": "Custom form",
  "fields": [
    {
      "name": "SCORE_ATB_OUI",
      "label": "test",
      "options": [
        {
          "label": "keine",
          "value": 0
        },
        {
          "label": "1",
          "value": 1
        }
      ],
      "dataType": "integer",
      "component": "select"
    },
    {
      "name": "tabs",
      "fields": [
        {
          "name": "ATB1",
          "title": "Antibiotikum 1",
          "fields": []
        },
        {
          "name": "ATB2",
          "title": "Antibiotikum 2",
          "fields": []
        }
      ],
      "component": "tabs",
      "actions": {
        "label": ["hideTabs", "SCORE_ATB_OUI"]
      }
    }
  ]
}

```

**Comment by anjalikalsariya** [comment]
Hello Folks,

Can you help with this I need to disable particular tab based on another field  value?

Thanks

**Comment by rvsia** [comment]
@anjalikalsariya 

Hello, this is not possible in any our tab component. You can either create your own custom TAB component supporting this behavior or you can use `condition` to display/show two different tab fields - one with disabled, one enabled - but that would require some copy-paste schema.

**Comment by anjalikalsariya** [comment]
Thanks @rvsia.

Okay got it.

Can you please share code example for the display/show tab using condition ?

**Comment by rvsia** [comment]
@anjalikalsariya Here is a small example https://stackblitz.com/edit/r7ptns-vhblea?file=schema.js

**Comment by anjalikalsariya** [comment]
Thanks @rvsia , Let me check
