### ISSUE TITLE
Refactor of defaultProps usages to use default parameters instead

### ISSUE THREAD

**Issue by danbrown7** [data-driven-forms/react-forms#1439]
**Scope**: All around the library

**Description**
When using numerous different components across the library, this error is received

Warning: FormTemplate: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

**Schema**
Any minimal schema which uses a MUI Text box or something will reproduce this

Is there a timeline for this refactoring/will it be occuring?

**Comment by Hyperkid123** [comment]
Hi @danbrown7 

> Is there a timeline for this refactoring/will it be occurring?

Not really. We had some plans to release a new major version of the packages, but it turned out there was no need for substantial changes.

So I think we should focus on the refactoring you have mentioned ASAP.

**Comment by Hyperkid123** [comment]
@danbrown7 can you share what packages and what versions you use?

**Comment by danbrown7** [comment]
> @danbrown7 can you share what packages and what versions you use?

I currently use
react-form-renderer
common
mui-component-mapper

All on version 3.22.1

**Comment by Hyperkid123** [comment]
@danbrown7 a new version with a fix should be released shortly.
