### ISSUE TITLE
Typo in documentation: FieldProvider

### ISSUE THREAD

**Issue by fdx-wayne-yeap** [data-driven-forms/react-forms#1443]
**Scope**: Documentation

**Description**

https://www.data-driven-forms.org/mappers/custom-mapper#fieldprovider

The documentation refers to "FieldProvider" but the code sample illustrates "FielProvider".

**Schema**

N/A

![image](https://github.com/data-driven-forms/react-forms/assets/60493677/cf00a6e7-5be2-415b-8127-965dab6840df)

**Comment by rvsia** [comment]
@fdx-wayne-yeap thank you for reporting this!
