### ISSUE TITLE
Required validator does not allow 0 as numeric value

### ISSUE THREAD

**Issue by Anders-Lind-Pedersen** [data-driven-forms/react-forms#1484]
**Scope**: Required validator does not allow 0 as numeric value

**Description**
It is not possible to use the required validator, and at the same time allowing 0 as a value in a numeric field.
https://stackblitz.com/edit/dt3gcp?file=schema.js

**Schema**

```JSON
{
    name: 'field1',
    label: 'Field 1',
    component: 'select',
    dataType: 'integer',
    options: [
      {
        label: 'Zero',
        value: 0,
      },
      {
        label: '1',
        value: 1,
      }
    ],
    validate: [
      {
        type: 'required',
      },
    ],
    clearOnUnmount: true,
    },
    {
    name: 'field2',
    label: 'Field 2',
    component: 'text-field',
    dataType: 'integer',
    type: 'number',
    validate: [
      {
        type: 'required',
      },
    ],
    clearOnUnmount: true,
}
```

**Comment by Hyperkid123** [comment]
It will need adjustments to the validator condition.  The issues going to be here: https://github.com/data-driven-forms/react-forms/blob/master/packages/react-form-renderer/src/validators/validator-functions.js#L5

We will need more than just `return value` as 0 is resolved to `false` in JS.

**Comment by rvsia** [comment]
@malloy045 Are you working over fork?

**Comment by malloy045** [comment]
> @malloy045 Are you working over fork?

@rvsia, no, I cloned the repo and created a new branch from master but I'm unable to push it to this repo.

**Comment by rvsia** [comment]
@malloy045 Yeah, you need to fork the repo and open a pull request from the fork to master.

**Comment by Anders-Lind-Pedersen** [comment]
Wow - this was fast. Great work - really appreciate it ;)
