### ISSUE TITLE
React Warning "Encountered two children with the same key" when conditionally disabling a field

### ISSUE THREAD

**Issue by malloy045** [data-driven-forms/react-forms#1491]
**Scope**: renderer

**Description**
We have a need to conditionally disable a field.  As suggested in [this comment](https://github.com/data-driven-forms/react-forms/discussions/1355#discussioncomment-4652840), we added two fields with inverse conditions where one is editable, and the other is not.  

When the form renders, we experience a warning in the console:
> Warning: Encountered two children with the same key, `field2`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

If this is a sanctioned solution, I would expect no warning and I would expect the framework to handle the keys.  If this is unreasonable, is there another solution?

**Code Sandbox**
https://codesandbox.io/p/sandbox/data-driven-forms-example-forked-jy2frp

**Schema**
```
{
  title: "Conditionally Disable",
  fields: [
    {
      component: componentTypes.TEXT_FIELD,
      name: "field1",
      label: 'type "disable" to disable the field',
      initialValue: "disable",
    },
    {
      component: componentTypes.TEXT_FIELD,
      name: "field2",
      label: "field2 (editable)",
      condition: {
        not: {
          when: "field1",
          is: "disable",
        },
      },
    },
    {
      component: componentTypes.TEXT_FIELD,
      name: "field2",
      label: "field2 (disabled)",
      isReadOnly: true,
      isDisabled: true,
      condition: {
        when: "field1",
        is: "disable",
      },
    },
  ],
}
```

**Comment by Hyperkid123** [comment]
Hello @malloy045. By default, we fall back to the `name` attribute to assign keys. In this, you have a duplicate name because of the condition. Which is fine. But you have to help React a bit. To fix this error you can simply assign a `key` attribute to the duplicate items I the schema to get rid of the warning.

**Comment by malloy045** [comment]
> Hello @malloy045. By default, we fall back to the `name` attribute to assign keys. In this, you have a duplicate name because of the condition. Which is fine. But you have to help React a bit. To fix this error you can simply assign a `key` attribute to the duplicate items in the schema to get rid of the warning.

@Hyperkid123 - Makes sense and is very obvious in hindsight (sorry for wasting your time).  Thank you!

**Comment by Hyperkid123** [comment]
No time wasted 😉 . Closing the issue.
