### ISSUE TITLE
Minimum date setting for date/datetime picker

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#150]
The dialog editor's date/datetime picker has a show past dates feature that, when it's set to false, doesn't allow you to select any date/datetime before Today(). As far as I analyzed the code, it is implemented as a minimum date passed to the component's backend. Would it be possible to have something similar? Either the minimum date exposed, or just an optional limit to select a future date?

Note that this is not a validation issue, but a problem with what can or can not be selected.

**Comment by Hyperkid123** [comment]
@skateman you can "black-list" dates:
```jsx
disabledDays: [{
  before: new Date(),
  after: new Date(),
}]
```
We are using http://react-day-picker.js.org/ which I've noticed is not mentioned in the docs.

How it now accepts only Date object not a string. I will fix that.

**Comment by skateman** [comment]
I'm good with the object for now, but probably if we go full JSON, the string is a better option.

**Comment by Hyperkid123** [comment]
@skateman is there some sort of special string format of dates? Or is it anything generally accepted by js `new Date()`

> I'm good with the object for now, but probably if we go full JSON, the string is a better option.

Its easy to sanitize

**Comment by skateman** [comment]
> is there some sort of special string format of dates?

No, there isn't and I'm okay with `new Date()` but please don't forget to document it properly. Also the time and date-time should be parseable.

**Comment by Hyperkid123** [comment]
It always returns `Date` object

**Comment by skateman** [comment]
Also we might need some kind of wildcards for `TODAY`, if that's possible. As I described above, in some cases the date can't be in the future and we can't really define a dynamic date in a JSON schema :confused:

**Comment by Hyperkid123** [comment]
Yep. `today` might be good enough
