### ISSUE TITLE
PF4 wizard: Show title for step in content

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#151]
In Sources-UI (cc @terezanovotna ) we need to show the title of the current step also in the body of the step.

So, I would like to add a option for wizard `showTitles`

```jsx
{
  ...wizardProps,
  showTitles: true
}
```

And for each step add a option `hideTitle` / `showTitle` which will hide(= override the `showTitles`)/show the title 

and `customTitle` - for cases, when a user need to provide different title for the body and for the navigation. For example, in the navigation you cannot use a title with an icon + popover.

```jsx
{
   ...stepProps,
   hideTitle: true,
   // or
   customTitle: React.node..
}
```

What do you think, @Hyperkid123 ?

**Comment by Hyperkid123** [comment]
Well if this is what we need :wink:
