### ISSUE TITLE
Dropdown doesn't play well with date picker in PF3

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#160]
![Screenshot from 2019-10-11 18-21-35](https://user-images.githubusercontent.com/649130/66667775-14b00a00-ec54-11e9-8ced-028a37285f32.png)

**Comment by epwinchell** [comment]
@skateman A similar issue was resolved/discussed here: https://github.com/ManageIQ/manageiq-ui-classic/pull/6264

cc\ @Hyperkid123

**Comment by Hyperkid123** [comment]
Thanks for bringing this up. I will check it ASAP.

**Comment by Hyperkid123** [comment]
I really don't understand why selector `.input-group .form-control` from pf3 has z-index value 2.
