### ISSUE TITLE
Data types don't play well with multiselects

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#169]
When setting a data type on the multiselect, it basically becomes unusable as not the individual selected items are forced to be a data type, but the whole array is being tested:

![Screenshot from 2019-10-18 08-15-02](https://user-images.githubusercontent.com/649130/67070131-84a42000-f17f-11e9-802b-31fb1c8a8987.png)

I think in this case the type enforrcement should be ran on each array member separately and reduced together using `AND`.

**Comment by Hyperkid123** [comment]
@skateman yep you are right. This will be fixed.
