### ISSUE TITLE
Consistency in top-level attributes of the schema

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#171]
I noticed that if you set a `description` on the top level of the schema, it gets rendered consistently with descriptions on lower levels. However, the `label` attribute is not getting rendered. 

So for example, the following schema:
```js
{
  label: 'Dialog editor demo',
  description: 'This is a demo of the new dialog editor that is based on Data Driven Forms',
  fields: [...]
}
```

Gets rendered like this:
![Screenshot from 2019-10-18 13-07-00](https://user-images.githubusercontent.com/649130/67089667-81715a00-f1a8-11e9-8ecb-71a48e925af6.png)

To be honest, I'm positively surprised that the `description` is rendered and I don't have to implement it, but I think the `label` should be rendered as well. However, I would totally understand if you don't want to render the `label`, but in this case you would have to do similarly with the `description`.

**Comment by rvsia** [comment]
Yeah, there is `title` prop, which works like that, but it makes sense to have `label` too to be consistent. Check the PR I made, I also updated docs to get this info clear. Thanks for the issue!
