### ISSUE TITLE
Validate field cannot be undefined

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#174]
@Hyperkid123 told me that there's no difference between a field not being specified or having its value as `undefined`. Well, it seems there is:

![Screenshot from 2019-10-18 18-10-48](https://user-images.githubusercontent.com/649130/67110276-a24ea500-f1d2-11e9-999b-e4b4375ea08f.png)

Should I have a special case for this, or can this be fixed somehow on your side?

**Comment by skateman** [comment]
I actually sorted this out, but it might be still a problem for you ... feel free to close it.

**Comment by Hyperkid123** [comment]
@skateman can you post the schema you used please?

**Comment by skateman** [comment]
```js
                {
                  name: 'username',
                  label: 'Username',
                  visible: true,
                  component: componentTypes.TEXT_FIELD,
                  dataType: dataTypes.STRING,
                  type: 'text',
                  validate: undefined
                },
```

**Comment by Hyperkid123** [comment]
Interesting. I will have to check it.

**Comment by Hyperkid123** [comment]
@skateman ok after checking this out the issue is not in the renderer but in the schema validator. It checks if there is a key `validate` and if there is it checks if the values type is na `Array`. Fixing now.
