### ISSUE TITLE
Problems with datepicker's submitted format and timezone

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#178]
The submitted value of the datepicker is always the "Zulu" military time, even if the selected value is displayed as a regular date. This time is equal to the UTC, so if you select *2019-10-19 11:46* in the timepicker, you will get *2019-10-22T09:46:00.000Z* to submitted.

We either need to submit a date object or a way to customize the submitted value (maybe based on the variant?) or an option to select from both.

**Comment by Hyperkid123** [comment]
@skateman you will always get Date object.

Are you sure about the time zone offset? I just tried it and got `Fri Oct 18 2019 14:16:00 GMT+0200 (Central European Summer Time)` which matches the timezone I am in.

Its base on the browser timezone.

**Comment by skateman** [comment]
Well, the problem is when you have just a date (no time) selector in UTC+2 timezone at 0:30 midnight and you select a date. If the server uses a different timezone, you might end up with a different date stored in the db. Again, because of the time ... which is not even part of the picker.

**Comment by skateman** [comment]
I tested this in the current dialog editor and the backend has some kind of compensation for this, so this is fine.
