### ISSUE TITLE
Opening a datepicker with a preset initialValue crashes

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#189]
The schema below throws an an `e.getTime is not a function` error:
```javascript
{
  component: componentTypes.DATE_PICKER,
  name: "date-picker-1",
  label: "Datepicker 1",
  initialValue: "2019-11-01T12:31:00.000Z",
  disabledDays: [
    {
      before: "today"
    }
  ],
  variant: "date"
}
```

**Comment by skateman** [comment]
My guess that this is PF3-specific, because I can't reproduce it on the live form editor in material.

**Comment by Hyperkid123** [comment]
@skateman ah. So i added support for string dates for the disabled days but not for initial values. Fixing asap.

**Comment by Hyperkid123** [comment]
btw the mui mapper is using completely different component by materiel ui. That is why its working.
