### ISSUE TITLE
Enable translations

### ISSUE THREAD

**Issue by Hyperkid123** [data-driven-forms/react-forms#221]
Add an API to form renderer for i18n.

Instead of forcing specific translation method, I think we should add a prop to FormRenderer:
- [ ] must be able to handle function (libraries like gettext)
  - this will return label as string to component
- [ ] must be able to handle React node (libraries like react intl)
  - this will return label as node
  - might break component styling
- [ ] anything else?

**Comment by rvsia** [comment]
Summary: we agreed to create an extension, which will rebuilt a schema to contain translated strings:

Advantages
- better testing (one input, one output)
- code on one place
- configurable without changing the schema
- no possibility of breaking changes

**Comment by Hyperkid123** [comment]
in v2 can yous action mapper
