### ISSUE TITLE
[Demo UX/UI] Inconsistent header levels

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#229]
Headers across pages are not consistent (see https://data-driven-forms.org/renderer/component-mapping vs https://data-driven-forms.org/renderer/renderer-api)

We need to decide styles for each level of heading:

```
  h1: props => <Heading { ...props } level={ 1 }/>,
  h2: props => <Heading { ...props } level={ 2 }/>,
  h3: props => <Heading { ...props } level={ 3 }/>,
  h4: props => <Heading { ...props } level={ 4 }/>,
  h5: props => <Heading { ...props } level={ 5 }/>,
  h6: props => <Heading { ...props } level={ 6 }/>,
```

Material-UI headers

![Screenshot from 2019-11-14 13-39-23](https://user-images.githubusercontent.com/32869456/68857935-3cc3da80-06e4-11ea-96fc-28092bb7f1ea.png)

I would start on level 4 (`h1 = level 4 ...`) or level 3 (but it seems to big to me also)

@doruskova @Hyperkid123

**Comment by Hyperkid123** [comment]
@rvsia starting on level `h4` from the DOM perspective is wrong. We have keep the `hx` hierarchy clean. What we can do is reduce the text size. We must always start at `h1` for primary title and go down from there. It will help the doc search crawler to create better indexes

**Comment by rvsia** [comment]
@Hyperkid123 Yes, I was talking about the font size = h1 should have size of material-ui level 4 (or 3...) and so on.

**Comment by doruskova** [comment]
@rvsia @Hyperkid123 I would start from h3 in material-ui. So, it should be 3rem (48/16px) with 0 letter spacing. h1 and h2 in material-ui looks too big.
