### ISSUE TITLE
Provide a way how to ignore empty values in Length validators

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#231]
**Description**

In Sources-UI I am using the same schema for adding/editing a source and ARN has to have minimal character count. However, because it is a 'password' value, I don't get the value from the API I can't repopulate the schema, so I cannot edit a source, because it is empty.

And even all other validators ignore empty values. 

So I think we should do either:

A) Ignore empty values 
or
B) Add an additional option to ignore empty values

I would love to do the first one (consistency and if user needs to have some value, he can always use the required validator), but it could bring breaking changes, so I think we should go the second way.

What do you think, @Hyperkid123?

**Comment by Hyperkid123** [comment]
Can you post an example schema? All validators should by default ignore empty values. If that is not the case then we should fix it.

**Comment by rvsia** [comment]
@Hyperkid123  https://data-driven-forms.org/renderer/validators#lengthvalidators

**Comment by rvsia** [comment]
So, should I fix it by ignoring empty values by default?

**Comment by Hyperkid123** [comment]
@rvsia yep
