### ISSUE TITLE
Provide propTypes object

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#232]
**Description**

When we are mentioning some arguments passed into a component/function in the documentation, we could also provide the exact propTypes.

For example: https://data-driven-forms.org/renderer/form-controls#formbuttonsrenderprops

We could write there a full propTypes object which an user could just copy, paste and use.

(Or make this object importable from some package - common?)

**Comment by Hyperkid123** [comment]
duplicate of #392
