### ISSUE TITLE
PF3: No helperText being rendered on checkboxes

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#250]
Maybe it's not even wanted, but noticed that:

```json
{
  "component": "checkbox",
  "name": "remember",
  "label": "Remember me",
  "visible": true,
  "helperText": "xxx"
}
```
ignores the `helperText`:
![Screenshot from 2019-12-03 07-20-01](https://user-images.githubusercontent.com/649130/70025456-695d6a80-159d-11ea-87c0-9ead837b4b36.png)

**Comment by skateman** [comment]
Okay, what about single checkboxes?

**Comment by rvsia** [comment]
@skateman `Description` works, `helperText` cannot be shown because the single checkbox does not have a standard label which contains the help icon.

**Comment by skateman** [comment]
I'm just wondering how does this fit into the PF3 specs :confused:

**Comment by Hyperkid123** [comment]
@skateman yeah i am wondering that myself. Is this usable in miq right now? Maybe we can use that for now.

- [ ] label

So this is how the single checkbox looks right now. Where would you put the question mark icon?

**Comment by skateman** [comment]
Umm, it's not working even on the old dialog editor. But in the dialogUser it looks like this:
![Screenshot from 2019-12-10 11-15-59](https://user-images.githubusercontent.com/649130/70547187-7bf81680-1b3e-11ea-992a-4a0698b045c4.png)

**Comment by Hyperkid123** [comment]
ok so the helper after

**Comment by Hyperkid123** [comment]
@rvsia can you add it to single checkbox?
