### ISSUE TITLE
URL validator: Cannot set custom message

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#251]
**Schema**

```
    {
      name: 'text_box_1',
      label: 'Text Box',
      title: 'Text Box',
      component: components.TEXT_FIELD,
      validate: [
        { type: validators.URL, message: 'bar' },
      ],
    },
```

**Expect behavior**

Show `bar`

**Current behavior**

Shows 'String is not URL.'

cc @Hyperkid123

**Comment by Hyperkid123** [comment]
@rvsia can you fix that?

**Comment by rvsia** [comment]
@Hyperkid123 yep, will do it

**Comment by Hyperkid123** [comment]
@rvsia so the issue is on this line: https://github.com/data-driven-forms/react-forms/blob/master/packages/react-form-renderer/src/validators/validator-mapper.js#L38

options are not being passed through. It should be an easy fix
