### ISSUE TITLE
PF3: Date picker icon regression after update

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#254]
I just noticed after updating my packages that the datepicker's icons for moving between months look different now:
![Screenshot from 2019-12-04 11-17-57](https://user-images.githubusercontent.com/649130/70135020-7fe0f000-1689-11ea-8d56-009a3517ddc7.png)

It used to be like this:
![Screenshot from 2019-12-04 11-19-30](https://user-images.githubusercontent.com/649130/70135033-85d6d100-1689-11ea-9997-2c3f79a0edfc.png)

ping @Hyperkid123

**Comment by rvsia** [comment]
It does on demo too https://data-driven-forms.org/component-example?component=date-picker

**Comment by Hyperkid123** [comment]
@skateman yep this was after PF update. @rvsia is taking care of that.
