### ISSUE TITLE
Possibility to wrap custom components via parametrization

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#257]
The [`shouldWrapInField`](https://github.com/data-driven-forms/react-forms/blob/master/packages/react-form-renderer/src/form-renderer/helpers.js#L14) function always returns `false` for custom components as `fieldComponents` is a pre-defined array. There is a way to wrap the custom component with a `FieldProvider` manually, however, it will not have the same effect with a decorated mapper (i.e. for editing).

```js
const previewFieldsMapper = Object.keys(formFieldsMapper).reduce((obj, key) => ({
  ...obj,
  [key]: PlayerField(formFieldsMapper[key]),
}), {});
```

The code above wraps pre-defined components as `FieldWrapper(PlayerField(Component))` while a custom component would end up `PlayerField(FieldWrapper(Component))`. This inconsistency causes a lot of trouble when creating custom components as I have to compensate all the pre-defined behavior outside. It would be easier if I could just customize the `shouldWrapInField`.

cc @Hyperkid123

**Comment by skateman** [comment]
The main issue with the wrapping order is that the `FieldWrapper` modifies the structure of the passed params, specifically `name` becomes `input.name`.

**Comment by Hyperkid123** [comment]
> The main issue with the wrapping order is that the FieldWrapper modifies the structure of the passed params, specifically name becomes input.name.

@skateman that is exactly how you are supposed to get these. All input specific props are inside `input` object even if the component is wrapped. The Field provider generates this automatically and adds a lot of critical props (like `onChange`) to it.

We actually want to remove `shouldWrapInField` entirely after we can move to hooks and use latest version of final form. So even the "officially" defined component will have to wrapped in Field Provider or use the hook to subscribe to the state.

> I have to compensate all the pre-defined behavior outside.

What exactly you have in mind there?

**Comment by skateman** [comment]
> So even the "officially" defined component will have to wrapped in Field Provider or use the hook to subscribe to the state.

I am okay with consistency, so if all components need to be wrapped the same way.
