### ISSUE TITLE
Multiselect dropdown with loadOptions doesn't allow selecting 

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#264]
If a dropdown is set to `multi` and the options are loaded through a promise with `loadOptions`, the component gets re-rendered anytime you select an option. This causes the inability to select anything.

@Hyperkid123

**Comment by rvsia** [comment]
Cannot reproduce this issue

**schema**

```jsx
{
    component: 'select-field',
    name: 'select-field-3',
    label: 'Dropdown 1 multi false simple value',
    loadOptions: () => fetch('https://dog.ceo/api/breeds/list/all').then(data => data.json()).then(data => data.message.hound.map((x) => ({
        label: x,
        value: x,
    }))),
    multi: true,
},
```

Everything works as it should.

![multiselect](https://user-images.githubusercontent.com/32869456/70703427-6fa3c300-1cd0-11ea-9103-1e1287e71bb2.gif)

**Comment by Hyperkid123** [comment]
@skateman does your component have key?

**Comment by skateman** [comment]
Doesn't work even with a `key` attribute

**Comment by skateman** [comment]
I added an empty `useEffect` with a `console.log` call and determined that the single select does 3 reloads for an open + select while the multiselect does 6.

Also a strange thing, if I have the field rendered as a single select and select a field, then changing it to multi -> it just works as it should.

**Comment by Hyperkid123** [comment]
Does your component have some state management inside of it?

**Comment by skateman** [comment]
https://github.com/ManageIQ/manageiq-ui-classic/pull/6506/files#diff-bd0ffa1799410bbea6710e45b1208823

**Comment by rvsia** [comment]
@Hyperkid123 @skateman so, should we close this issue? This repository doesn't seem to be the right place to discuss the issue.

**Comment by Hyperkid123** [comment]
I will try to reproduce it in clean project

**Comment by Hyperkid123** [comment]
@skateman ok so the issue is in the React.cloneElement part which is used when passing children to custom component.

To fix it you have two options:
```jsx
 <FieldProvider {...rest} render={props => <RawTagControl {...props} /> }>

 <FieldProvider {...rest} component={RawTagControl} />
```

I am not 100% sure what is the cause, but this worked for me. @rvsia  We should add to the docs that using the `component` prop is the n.o 1 option and render is the n.o 2.

**Comment by skateman** [comment]
It works, thank you!
