### ISSUE TITLE
Provide option to call change from outside/initialChange

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#275]
**Scope**: FormRenderer

**Description**

In Sources UI I have this following flow:

`[ FORM ]` > submit :incoming_envelope:  > :boom: :skull_and_crossbones:  > `[ ERROR_PAGE ]` > retry button :recycle:  > `[ FORM ]`

The form has set initialValues. In the submit action, form values and initial values are compared and only modified values are sent to an API.

I need to re-set the values when restarting the form after an error occurs (formValues from the first attempt set in the second attempt). However, I cannot use the initial values, because I am using them to compare new values with initials. (So in the second attempt: formValues = initialValues = no values :sob: )

I propose two ways how to solve this riddle:

1st ) Provide a way how to call `onChange` outside the form

2nd and maybe preferred ) Provide something like initialChange, which will be called only once and will call `change` event with provided values after the form renderer is mount

**Schema**

```jsx
  <FormRenderer
    schema={schema}
    formFieldsMapper={formFieldsMapper}
    layoutMapper={layoutMapper}
    onSubmit={console.log}
    initialValues={{
       name: 'Mike Johnson'
   }}
    initialChange={{
        name: 'John Smith'
    }}
  />
```

=> modified fields: name

What do you think, @Hyperkid123 :space_invader: :one: :two: :three:  ?

**Comment by Hyperkid123** [comment]
You can use `initialize` from the second submit argument.

**Comment by rvsia** [comment]
The `initialize` from submit won't work as the second form is different 'instance'.

**Comment by Hyperkid123** [comment]
I see. Store the submit value then and use them as initial values for the next instance?

**Comment by rvsia** [comment]
As I said, the problem is that I need to get dirty fields to know which values have been modified by user.

**Comment by Hyperkid123** [comment]
would https://final-form.org/docs/react-final-form/types/FormProps#keepdirtyonreinitialize help? Is it possible to use initialize at all?

**Comment by rvsia** [comment]
What about to do something like

```jsx
  <FormRenderer
    schema={schema}
    formFieldsMapper={formFieldsMapper}
    layoutMapper={layoutMapper}
    onSubmit={console.log}
    initialValues={{
       name: 'Mike Johnson'
   }}
    onMount={
    (formOptions, ...otherthings) => formOptions.onChange(blablabla)
    }
  />
```
?

**Comment by Hyperkid123** [comment]
That is a bit better but I would still like to avoid it if possible.

Why is it a problem comparing the first initial values with the second instance of the form? You must have them somewhere. You don't need "dirty" metadata for that I think.

**Comment by rvsia** [comment]
It is possible to compare the first initialValues, and second ones in the submit action but I am just trying to find some clean and simple solution. Alright, I will do it other way, thanks for discussing this! This can be closed now.

**Comment by Hyperkid123** [comment]
The thing is this behavior is very specific. I did play with the idea of exposing the formApi from the get-go but ultimately decided against it and I will be until someone finds some use-case where there is no other way :D. To be clear the above-proposed solutions are not that simple and clean to implement inside the renderer I tried.
