### ISSUE TITLE
Do MUI mapper audit

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#295]
**Scope**: MUI MAPPER

**Description**

- [componentTypes.TEXT_FIELD] :eyes: 
  - [x] tests
  - [x] validation errors
  - [x] isRequired
  - [x] isDisabled
  - [x] isReadOnly
  - [x] helperText
  - [x] description (?)
  - [x] placeholder
- [componentTypes.TEXTAREA_FIELD] :eyes:
  - [x] tests
  - [x] validation errors
  - [x] isRequired
  - [x] isDisabled
  - [x] isReadOnly
  - [x] helperText
  - [x] description (?)
  - [x] placeholder
- [componentTypes.SELECT_COMPONENT] :eyes:
  - [x] missing label :(
  - [ ] tests
  - [x] validation errors
  - [x] isRequired
  - [x] isDisabled
  - [x] isReadOnly
  - [x] helperText
  - [x] description (?)
  - [x] isClearable
  - [x] isSearchable
  - [x] isMulti (multi!)
  - [ ] loadOptions
  - [x] placeholder
- [componentTypes.CHECKBOX] :eyes:
  - [x] tests
  - [x] validation errors **error replaces the label**
  - [x] isRequired
  - [x] isDisabled
  - [x] isReadOnly
  - [x] helperText
  - [x] description (?)
- [componentTypes.CHECKBOX] multiplecheckbox  :eyes:
  - [x] tests
  - [x] validation errors
  - [x] isRequired
  - [x] isDisabled
  - [x] isReadOnly
  - [x] helperText
  - [x] description (?)
- [componentTypes.SUB_FORM] :green_heart: 
  - [x] tests
  - [x] description (?)
- [componentTypes.RADIO] :eyes:
  - [x] tests
  - [x] validation errors
  - [x] isRequired
  - [x] isDisabled
  - [x] isReadOnly
  - [x] helperText
  - [x] description (?)
- [componentTypes.TABS] :eyes:
  - [x] tests
  - [ ] description (?)
- [componentTypes.DATE_PICKER] :eyes:
  - [x] tests
  - [x] validation errors
  - [x] isRequired
  - [x] isDisabled
  - [x] isReadOnly
  - [x] helperText
  - [x] description (?)
  - [x] placeholder
  - [x] missing date format
- [componentTypes.TIME_PICKER]  :eyes:
  - [x] tests
  - [x] validation errors
  - [x] isRequired
  - [x] isDisabled
  - [x] isReadOnly
  - [x] helperText
  - [x] description (?)
  - [x] placeholder
  - [x] missing date format
- [componentTypes.SWITCH] :eyes:
  - [x] tests
  - [x] isDisabled
  - [x] isReadOnly
  - [x] helperText
  - [x] description (?)
  - [x] onText
  - [x] offText
- [componentTypes.PLAIN_TEXT] :green_heart: 
  - [x] tests
- [componentTypes.WIZARD] :no_entry: 
  - [ ] completely missing

cc @Hyperkid123

**Comment by Hyperkid123** [comment]
completed in v2
