### ISSUE TITLE
Unclear how to display form-level submit errors

### ISSUE THREAD

**Issue by duanewood** [data-driven-forms/react-forms#304]
FormRenderer

Field level submit errors are handled properly and are displayed in the fields, but form-level errors are not displayed (like final form "FORM_ERROR").

Should these be handled outside the form? -- or should it be rendered using components similar to form title and description?

**Comment by Hyperkid123** [comment]
@duanewood currently there is no way to display form-level errors. We did require this feature up until this point. We support form-level validation we should support form-level error messages.

I think that adding a new component to the mapper (error wrapper?) is probably the way to go. I think that creating a component like this should not take long.

Do you have something in mind or should we just come up with something and iterate over it?

**Comment by rvsia** [comment]
Yeah, I agree with creating additional components. Each design system can have different form errors so it shouldn't be coded into the renderer itself. (Patternfly packages use inline notification at the top of the form, but I can imagine other packages can use notifications above buttons, etc...)

**Comment by duanewood** [comment]
For now, I can handle the errors as a side-effect of submit and show the errors below the form, but I would prefer to show them above the buttons.  Since form-level errors can come from the validate function or from submit, it should be handled in the framework.

One option could be to add a new layoutComponent ("FORM_ERROR_MESSAGE") and maybe an optional FormRenderer param like formErrorMessage that could be one of "none" (don't display), "aboveForm", "belowForm" (default) that controls if and where the message is displayed.

I also think it would be good to pass the form meta data object to the FORM_WRAPPER component.  This would allow the form component to render the form error message if submitFailed, a spinner if submitting, etc.

A more involved option could be to create a template layout component that gets passed the various components (title, description, form, formErrorMessage, FormControls) that could support custom layouts.

**Comment by rvsia** [comment]
@duanewood 

If you need to show errors above buttons, you have two options how you can achieve that right now:

1) Use [custom form controls](https://data-driven-forms.org/renderer/form-controls), that have access to formState, so you can add the spinner when submitting, show errors above buttons, etc.

2) Create custom component which show errors in formFieldsMapper and put it in the schema above buttons.

---

I like the idea with template layout. With using something like that, there would be no need to introduce new layout components (and new props as well) as everyone could put there everything they need. It's something we can introduce in the next major release, @Hyperkid123. (Also, we have merging layout and form fields mappers together in our plan.)

**Comment by Hyperkid123** [comment]
@duanewood, for now, I would probably do the same as Richard said. Either option is OK.

> I also think it would be good to pass the form meta data object to the FORM_WRAPPER component.

This is an interesting idea. The only thing that has to be considered here is the subscription. Right now, the form is subscribed only to a couple of events so it would limit the metadata update. Now we do allow changing the subscription object so you would have to handle that on your own, which is fine I think.

Also introducing the template layout sounds great. But I think that is something that should be introduced with next breaking changes (we plan to start working on that soon, mostly introduces hooks and removal of some stuff we found out that are not useful).

@duanewood should we create some example of how to create the form-level level? Or do you want to do that yourself. I think it would be great addition to the docs.
