### ISSUE TITLE
PF3: hidden field has a title displayed

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#319]
```js
  {
    component: componentTypes.TEXT_FIELD,
    name: 'type',
    label: __('Type'),
    type: 'hidden',
  }
```

![Screenshot from 2020-02-21 14-39-51](https://user-images.githubusercontent.com/649130/75039018-0d2d2700-54b8-11ea-80f9-e01ba2ebf0fb.png)

**Comment by rvsia** [comment]
Try to set `hideLabel: true`

**Comment by skateman** [comment]
Well, that doesn't really fix the semantical problem...but ok

**Comment by rvsia** [comment]
If you need to hide the whole field, just use `hideField`. `type` is a prop which is passed only to the input and it's not controlled by DDF.

**Comment by Hyperkid123** [comment]
@skateman the type ties to the HTML equivalent of input. But the label is a completely different HTML element. If you don't want to show the label you have multiple options. I would leave the label `undefined`.

What you expect is basically that type hidden input should somehow hide label element:

```HTML
<div>
  <label htmlFor="hidden-field">I am label</label> <!-- this will be visible -->
  <input type="hidden" value="foo" name="hidden-field" />
</div>
```

**Comment by skateman** [comment]
I found a solution, but do you really have a practical use of displaying the `label` when the field is `type: hidden`?

**Comment by Hyperkid123** [comment]
No, not really. But you can still do it. As you can in HTML, JSX, HAML, etc.
