### ISSUE TITLE
dual-list-select is not available in PF4

### ISSUE THREAD

**Issue by chambridge** [data-driven-forms/react-forms#358]
**Scope**: PF4 dual-list-select

**Description**
Attempted to use `dual-list-select` in a PF4 app and hit the following error:
![dual-list-select](https://user-images.githubusercontent.com/29379759/76083389-82e6c780-5f7b-11ea-8e23-9cc78e8f0ff5.png)

**Schema**

Use the example from here:
https://data-driven-forms.org/others/miq-components#duallistselect

**Comment by rvsia** [comment]
@chambridge Do you have any special requirements for this component?

**Comment by chambridge** [comment]
So we want to use it to allow users to specify what OpenShift labels they want to summarize data on for improved performance, querying, and filtering.

So here the user would have a list of the available OpenShift labels (on left) and they would move them to the right side to select as enabled for summarization, grouping and filtering.

<img width="606" alt="image" src="https://user-images.githubusercontent.com/29379759/76083770-53848a80-5f7c-11ea-975a-65023dffb118.png">

I don't believe there are any special requirements.

**Comment by Hyperkid123** [comment]
@rvsia I think we might want to add this one to all mappers. It's a common component. And with the changes in V2 we don't have to worry about bloating the build sizes.

**Comment by chambridge** [comment]
So the following needs to be bumped to the latest to pull in this change, correct?
https://github.com/RedHatInsights/settings-frontend/blob/master/package.json#L7-L8

**Comment by rvsia** [comment]
@chambridge Yes.
