### ISSUE TITLE
renderer: Initial value data type is not applied on the field.

### ISSUE THREAD

**Issue by Hyperkid123** [data-driven-forms/react-forms#376]
**Scope**: Renderer

**Description**
The initial value data type is not applied in the field.

**Schema**
```jsx
{
  component: 'text-field',
  name: 'integer-type',
  dataType: 'integer',
  initialValue: '5'
}
```

The initial value should be converted before its set as an initial value of a field.

**Comment by rvsia** [comment]
Is this really a bug? Sounds more like user's mistake.

**Comment by Hyperkid123** [comment]
You can have input type text with integer dataType. I would stick with treating this a bug since everything is a string.
