### ISSUE TITLE
Component for defining N mapping rules

### ISSUE THREAD

**Issue by chambridge** [data-driven-forms/react-forms#378]
**Scope**: 
PF4 mapper, Form renderer

**Description**
I would like to be able to define mapping rules for so we can normalize Cloud Provider tags & OpenShift labels.

Ideally we could have a:
 **select-field** `=` **text-field**
and
  **select-field** **text-field** `=` **text-field**
and be able to add N of these rules.

The first would enable us to select a tag key and provide a mapping to a new tag key,
The second would enable us to select a tag key and enter a value and then provide a mapping to a new value.

Tag key mapping:
- env => environment
- environment, prod => production

**Comment by rvsia** [comment]
It sounds like it could be done with using of FieldArray https://data-driven-forms.org/renderer/field-array#pf4implementation

**Comment by Hyperkid123** [comment]
@chambridge One thing that should b pointed out is that there is no official PF design for dynamically adding form fields. Maybe we can ask for help to polish it a bit.

**Comment by rvsia** [comment]
@chambridge This issue has been opened for months with no progress, so let's close it for now. Feel free to reopen if FieldArray component is not sufficient enough or if you need any help with implementing it.

Thank you for understanding.
