### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by carlosthe19916** [data-driven-forms/react-forms#392]
Is there any plan to support Typescript?

**Comment by Hyperkid123** [comment]
@carlosthe19916 We do not plan it right now. We are not in the middle of refactoring to eliminate some design mistakes we did and improve overall quality of the library and code.

That said after that is we want to introduce features to also improve the developer experience as well. Exporting typings from components and functions is the obvious first step. I don't know about converting the whole codebase to typescript.

What would you expect?

**Comment by carlosthe19916** [comment]
@Hyperkid123 Thanks for the quick reply... I think my expectations are to be able to use Data Driven Forms in the same way as I use Patternfly React components https://github.com/patternfly/patternfly-react/

**Comment by Hyperkid123** [comment]
Ok so you are probably mostly interested in typings and code splitting. Code splitting is comming in v2 and prop typings will follow soon after that.
