### ISSUE TITLE
Optional reprioritization of initialValue vs initialValues

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#393]
You can specify initial form field values either on the form field using `initialValue` or by passing all of them as an object as `initialValues` to the form renderer. The field-level `initialValue` has a priority over the global `initialValues` which causes problems if you're using the `initialValues` to load data from an external source.

I am suggesting to create a new prop on the form renderer to optionally swap the priority of these two:
```js
initialValuePriority=["renderer", "field"] // default "field"?
```

@Hyperkid123

**Comment by Hyperkid123** [comment]
@skateman is this still viable? I think the issue was resolved in a newer version.
