### ISSUE TITLE
The helperText is being displayed differently on the newest version 

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#417]
This is not the first time this happened, helperText used to look like this:
![Screenshot from 2020-04-02 12-22-44](https://user-images.githubusercontent.com/649130/78238282-b23a1700-74dc-11ea-81d4-8ae61a18851e.png)

Now after the update to 1.30.0, it looks like this:
![Screenshot from 2020-04-02 12-22-28](https://user-images.githubusercontent.com/649130/78238294-b5cd9e00-74dc-11ea-8b6e-c70907a53ac3.png)

**Comment by skateman** [comment]
@Hyperkid123 @rvsia why are we keep swinging between these two? Can't we have a spec that catches all unexpected changes?

**Comment by rvsia** [comment]
What was your previous version?

This has been changed in this PR https://github.com/data-driven-forms/react-forms/pull/156 in October because of you.

**Comment by skateman** [comment]
1.18.0

**Comment by rvsia** [comment]
Yeah, it was added in 1.19.0.

**Comment by skateman** [comment]
OK
