### ISSUE TITLE
Can't get library to work based on docs

### ISSUE THREAD

**Issue by dave-calleja** [data-driven-forms/react-forms#418]
**Scope**:
Imports of from renderer and mappers do not work.

**Description**
Copying the example available on the homepage (https://data-driven-forms.org/) results in imports errors, the initial one being:

```
Could not find module in path: '@data-driven-forms/react-form-renderer/dist/cjs/component-types' relative to '/node_modules/@data-driven-forms/pf4-component-mapper/dist/cjs/index.js'
```

Example can be seen on https://codesandbox.io/s/competent-sara-4hrxx

**Schema**
Could not even get to a point where a form is rendered!

**Comment by dave-calleja** [comment]
Some more info: It seems installing the library without a specific version defaults to `v1.31.1` for some reason. This seems to be the source of the errors experienced.

**Comment by Hyperkid123** [comment]
@dave-calleja the latest version should be 2.0.x. We released a backported fix to v1 with the version 1.31.1. I think I forgot to add npm tag to mark it deprecated so it defaults older version.

Let me fix that.

In the meantime, you can try to manually set the version 2.0.5

**Comment by rvsia** [comment]
Yeah, 2.x versions are not compatible with 1.x versions. 

1.31.1 was released after 2.0.5 and npm lists it as the last version, that's probably why it was used as the default. https://www.npmjs.com/package/@data-driven-forms/react-form-renderer Can you please take a look, @Hyperkid123 ?

To get this demo work you have to also install Patternfly 4 react + css. We should probably add it to the demo too.

**Comment by dave-calleja** [comment]
Yup I can confirm, installing Material UI or pattern fly (react) in addition to installing v2 version of react form renderer works fine :)

Thanks!

**Comment by Hyperkid123** [comment]
@dave-calleja thanks for finding out this issue :+1:

**Comment by Hyperkid123** [comment]
> 1.31.1 was released after 2.0.5 and npm lists it as the last version, that's probably why it was used as the default. https://www.npmjs.com/package/@data-driven-forms/react-form-renderer Can you please take a look, @Hyperkid123 

I will make v1 as deprecated. We should encourage migrating to V2 even though we still support it. That will set the default version on npm to 2.0.5

**Comment by Hyperkid123** [comment]
@dave-calleja should be also fixed once https://github.com/data-driven-forms/react-forms/pull/420 finished the release on CI.

**Comment by Hyperkid123** [comment]
Latest npm version is now set to `v2.0.6`
