### ISSUE TITLE
Docs for version 1.x still available anywhere?

### ISSUE THREAD

**Issue by tpinne** [data-driven-forms/react-forms#430]
Are the docs for the old version 1.x somewhere still available? We're right before a release of a new project and the deadline doesn't allow us to refactor to V2 before launch.

But to figure out some edge cases, bugs or misbehavior in our implementation it would be great to still have the old docs somehow accessible.

**Comment by rvsia** [comment]
Hi, thanks for opening this issue!

docs are available here https://pokus-next.firebaseapp.com/
or you can use old branch on github https://github.com/data-driven-forms/react-forms/tree/v1/packages/react-renderer-demo/src/app/pages

We are still releasing bugfixes, these versions are labeled as deprecated in NPM https://www.npmjs.com/package/@data-driven-forms/react-form-renderer

**Comment by Hyperkid123** [comment]
@tpinne yup the docs are still up. I understand that now it might not be the right time to migrate to v2, but I would strongly recommend doing so in the near future. We fixed up a lot of design mistakes and cleaned up the code substantially.

The schemas did not change that much, mostly we changed just some constants to make it more consistent. Most of the work would be with the form templates and component mapper if you are using your own.

There is also the migration guide in the docs.

**Comment by tpinne** [comment]
Thx for that info. And great task to pin it.

The release is somewhere next week. And that time frame is too small to introduce such a "big" refactoring and retesting. Therefore this will be postponed after the release with less stress on our shoulders. But it definitely will be done, because the project is the groundwork for more to come.
