### ISSUE TITLE
Add Slider/range components

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#472]
**Scope**: All mapers

**Description**

Slider is one of basic input types and it's commonly used across webs https://www.w3schools.com/tags/att_input_type_range.asp

I think we should add it as an another component types

**Schema**

```jsx
{
   components: componentsTypes.SLIDER,
   name: 'radius',
   min: 0,
   max: 100,
   step: 1,
   label: 'Select radius of your pizza delivery (km)'
}
```

**References**

MUI https://material-ui.com/components/slider/#slider
PF3 https://patternfly-react-pf3.surge.sh/?path=/story/patternfly-react-forms-and-controls-slider--slider
PF4 https://patternfly.github.io/v4/design-guidelines/usage-and-behavior/data-input#slider *coming soon*

What do you think @Hyperkid123 ?

**Comment by Hyperkid123** [comment]
@rvsia yup
