### ISSUE TITLE
Select with isClearable need click twice on iOS Safari 

### ISSUE THREAD

**Issue by roytan883** [data-driven-forms/react-forms#531]
**Scope**: 

"@data-driven-forms/mui-component-mapper": "2.4.4",
"@data-driven-forms/react-form-renderer": "2.4.4",

**Description**

Select with isClearable need click twice on iOS Safari to popup 

**Schema**

{
      "component": "select",
      "label": "gender",
      "name": "gender",
      "simpleValue": true,
      "isClearable": true,
      "options": [
        {
          "label": "male",
          "value": "male"
        },
        {
          "label": "female",
          "value": "female"
        }
      ]
    },

**Comment by rvsia** [comment]
Thanks for reporting this!

This bug also affects all other devices, as the `clearable` button is always shown.

Please see this PR https://github.com/data-driven-forms/react-forms/pull/532
