### ISSUE TITLE
mui -> select set isRequired: true no work

### ISSUE THREAD

**Issue by roytan883** [data-driven-forms/react-forms#534]
**Scope**: 

"@data-driven-forms/mui-component-mapper": "2.4.5",
"@data-driven-forms/react-form-renderer": "2.4.5",

**Description**

`select` set `isRequired: true` no work, if click submit directly, no warning popup out. But normal `text-field` set `isRequired` works

**Schema**
```
{
          "component": "select",
          "label": "gender",
          "name": "gender",
          "isRequired": true,
          "simpleValue": true,
          "options": [
            {
              "label": "male",
              "value": "male",
            },
            {
              "label": "female",
              "value": "female",
            }
          ]
        },
```

**Comment by rvsia** [comment]
Actually, the popup warning should not be shown.

As DDF contains custom validation logic, the HTML form validation should not be used. `isRequired` props serves only to indicate if the input is or is not required. (In MUI it just adds `*` to labels.) However, the material-ui is using the same prop to add the asterisk + to add the HTML validation, that creates this side-effect. To disable this, you have to set `noValidate` prop on a form component to disable the HTML validation. It set by default in the provided `formTemplate`. (If you are experiencing this using the default formTemplate, let us know please.)

```jsx
<form noValidate {...} >
     ....
</form>
```

Here is an example about using the required validator:

https://data-driven-forms.org/renderer/validators#requiredvalidator

```
{
   component: 'text-field',
   label: 'required field',
   name: 'name',
   isRequired: true,
   validate: [{type: 'required'}]
}
```

**Comment by roytan883** [comment]
@rvsia But, why this can work? The warning popup
```
{
          component: "text-field",
          name: 'name',
          label: 'name',
          isRequired: true,
          type: 'string',
          validate: [
            {
              type: "min-length",
              threshold: 2,
              message: '>2',
            },
            {
              type: "max-length",
              threshold: 10,
              message: '<10',
            },
          ]
        },
```

The problem is that, at the same env, why `text-field` popup warning, but `select` is not.

**Comment by rvsia** [comment]
@roytan883 

I cannot reproduce the popup using your schema: https://stackblitz.com/edit/pnghp6

What FormTemplate component do you use? 

```
<FormRenderer
          schema={schema}
          FormTemplate={FormTemplate} // ???
          componentMapper={componentMapper}
          onSubmit={console.log}
/>
```

**Comment by Hyperkid123** [comment]
@roytan883 

This happens because the actual select component does not have any HTML validation. The `select` component is not a native HTML element. We are using [autocomplete](https://material-ui.com/components/autocomplete/#autocomplete) component to be able to provide all the features.  That is the reason why HTML validation does not work on it. This will be the case with any non HTML form components.

This is why we use `required` purely as a visual indication and you have to combine it with the required validator in the `validate` array. Otherwise, you will have validation issues.

If you want to use native validation, you can swap your select in your component mapper for the native version of MUI select: https://material-ui.com/components/selects/#native-select and disable the `noValidate` prop inside your FormTemplate.

**Comment by roytan883** [comment]
@rvsia @Hyperkid123 Thanks, `validate: [{type: 'required'}]` works. It disable submit button by default.
Maybe the doc need clarify this, some component `isRequired: true` not work, need `validate: [{type: 'required'}]`

**Comment by roytan883** [comment]
close it now

**Comment by Hyperkid123** [comment]
@roytan883 docs need a lot of work. It would be valuable to get as much feedback as we can. We plan to do an overhaul to the structure and content. So if you have any suggestions feel free to open an issue. We would be very grateful.

I will close this one.
