### ISSUE TITLE
[PF4] Migrate away from react-select

### ISSUE THREAD

**Issue by Hyperkid123** [data-driven-forms/react-forms#560]
**Scope**: PF4 mapper

**Description**
The react select is now not necessary component because we have all the required logic inside the common code

I would like to use some different libraries (rc-select, downshift, ...) which is lightweight and allows us to customize the component. In an ideal scenario, we would use PF provided component, but that has performance and customization issues that do not allow us to use it at its current state.

**Comment by Hyperkid123** [comment]
We should probably use: https://github.com/downshift-js/downshift#installation
This should give us good enough flexibility to apply all PF4 styling while providing all the features with good enough performance.

**Comment by rvsia** [comment]
I think we could change the common select into some sort of hook during this transition:

```
const [ options, onInputChange, isFetching, selectedValue, handleChange ] = useSelect(props);
```

The common select now wraps the component with many redundant `react-select` props, so, for example, it's hard to get it to use in Blueprint mapper, because I would like to use only the async functionality, not the rest of props.

**Comment by Hyperkid123** [comment]
Yes we can do that. I think that will be a next step after we replace the react-select. I see a lot of strange props that we don't need or have unreasonable type

**Comment by Hyperkid123** [comment]
Current progress

![Screenshot from 2020-06-17 16-04-48](https://user-images.githubusercontent.com/22619452/84908084-4ebf8e80-b0b4-11ea-8fad-66b248516c59.png)
