### ISSUE TITLE
Hierarchial subsections

### ISSUE THREAD

**Issue by KaappoRaivio** [data-driven-forms/react-forms#570]
**Scope**: Schema 

**Description**
Is there a way to divide my form into hierarchial (nested) subsections using only the schema? 

Currently I'm using a workaround with PLAIN_TEXT elements as subsections, but this approach has many issues, mainly that the styling looks wrong, as I'd like the nested content to live inside the section div borders.

**Comment by rvsia** [comment]
Hello, thanks for the question!

You can divide the form using default [sub-form components](https://data-driven-forms.org/component-example/sub-form).

```jsx
    {
      "component": "sub-form",
      "title": "Subform",
      "description": "This is a subform",
      "name": "subform",
      "fields": [
        {
          "name": "carrot",
          "label": "Carrot",
          "component": "text-field"
        }
      ]
    }
```

Or you can easily implement [your own component](https://data-driven-forms.org/renderer/field-provider):

```jsx
import { useFormApi } from '@data-driven-forms/react-form-renderer';

const Section = ({fields}) => {
   const { renderForm } = useFormApi();

   return (<div>
    {renderForm(fields)}
  </div>);
}
```

**Comment by KaappoRaivio** [comment]
Seems to work. Thanks!
