### ISSUE TITLE
validatorTypes.MIN_ITEMS validation does not work when the list is empty

### ISSUE THREAD

**Issue by jessieweiyi** [data-driven-forms/react-forms#607]
**Scope**:  Form renderer

**Description**

The validation validatorTypes.MIN_ITEMS is not working for FieldArray when the list is empty. The submission happens. When you add one item, the validation works. 

**Schema**
I can reproduce the issue by putting the following schema in this page: https://data-driven-forms.org/component-example/field-array

```
export default {
  "fields": [
    {
      "component": "field-array",
      "name": "minItems",
      "label": "A list with a minimal number of items",
      "validate": [
        {
          "type": "min-items",
          "threshold": 3
        }
      ],
      "fields": [
        {
          "component": "text-field",
          "label": "Item"
        }
      ]
    },
  ]
};
```

<If it's possible, please provide a schema which reproduces the issue>

**Comment by Hyperkid123** [comment]
Hi @jessieweiyi, thanks for the issue.

Field array validators follow the same pattern of validators for normal fields and the values are not checked if empty. If you want to force that user must add some items, add the required validator to the validate array 
```
validate: [{ type: validatorTypes.MIN_ITEMS, threshold: 3 }, {type: validatorTypes.REQUIRED, message: "Validation message"}],
```

See example here: https://codesandbox.io/s/dark-sky-h6glg

**Comment by jessieweiyi** [comment]
> Hi @jessieweiyi, thanks for the issue.
> 
> Field array validators follow the same pattern of validators for normal fields and the values are not checked if empty. If you want to force that user must add some items, add the required validator to the validate array
> 
> ```
> validate: [{ type: validatorTypes.MIN_ITEMS, threshold: 3 }, {type: validatorTypes.REQUIRED, message: "Validation message"}],
> ```
> 
> See example here: https://codesandbox.io/s/dark-sky-h6glg

Thank you. It works.
