### ISSUE TITLE
TSC failed since version 2.6.0

### ISSUE THREAD

**Issue by jessieweiyi** [data-driven-forms/react-forms#610]
**Scope**: Form renderer

**Description**
I am trying to bump the version of the data driven form to the latest version. I got the following error when I am running tsc on my project:

```
node_modules/@data-driven-forms/react-form-renderer/dist/cjs/index.d.ts:48:1 - error TS2308: Module './renderer-context' has already exported a member named 'FormOptions'. Consider explicitly re-exporting to resolve the ambiguity.

48 export * from './wizard-context';
```

I have tried to install version by version. The issue presented from version 2.6.0.

**Comment by Hyperkid123** [comment]
Will take a look ASAP. cc @rvsia

**Comment by Hyperkid123** [comment]
@jessieweiyi new version will be released in a couple of minutes

**Comment by rvsia** [comment]
@jessieweiyi Thank you for reporting this! We are still struggling with a way how to automatically check if our TypeScript definitions are OK. If you encounter any additional issues, please let us know.
