### ISSUE TITLE
Option with empty value never gets selected in the DDF select

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#615]
**Scope**: DDFv1 PF3

**Description**
> In select fields, when there's a nulll/0/empty value for an option, it never gets preselected if the field matches the value and the placeholder is shown. If you try to select it manually, the same thing happens, the default empty value tied to the placeholder takes preference.

https://github.com/ManageIQ/manageiq-ui-classic/issues/7174

**Comment by skateman** [comment]
Any update on this @Hyperkid123?

**Comment by Hyperkid123** [comment]
The update is I will look at it. Sorry, too much stuff.

**Comment by Hyperkid123** [comment]
@skateman the issue should be fixed by https://github.com/data-driven-forms/react-forms/pull/829/. We are waiting for your ack.
