### ISSUE TITLE
[ANT] Add ant-mapper to demo page

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#621]
TODO:
- [ ] add ant mapper page to mappers section (installation, npm link, link to website)
- [ ] add ant mapper logo to landing page
- [ ] add stackblitz templates for ant mapper
- [ ] add ant option to component examples
- [ ] update generic example texts to include links to ant

**Comment by rvsia** [comment]
@Arun-42 Hey, do you want to take this task?

With a deadline, let's say, 14th July.

**Comment by rvsia** [comment]
Ant was releases as pre-release with this version: `@data-driven-forms/ant-component-mapper@0.0.1`

**Comment by Arun-42** [comment]
@rvsia Yes, I want to take up this issue.

**Comment by rvsia** [comment]
`@data-driven-forms/ant-component-mapper@0.0.2` is published. It contains all components.

**Comment by Hyperkid123** [comment]
@Arun-42 it might cause some issues to use the `latest` tag in package.json for the stack blitz template. The 0.0.2 release is tagged as beta so use explicit version in the template for now. We will use the latest tag once there is a stable release for the ant mapper.
