### ISSUE TITLE
We could introduce componentTypes.PASSWORD_FIELD

### ISSUE THREAD

**Issue by miha-plesko** [data-driven-forms/react-forms#64]
Currently it's possible to hide content of `componentTypes.TEXT_FIELD` type component by adding final form property:

```
type: 'password'
```
```
{
  component: componentTypes.TEXT_FIELD,
  name: 'password',
  label: __('Password'),
  type: 'password'  // <--------------------
}
```

But introducing a new field type e.g. `componentTypes.PASSWORD_FIELD` would be more intuitive I think. Also, having this as a separate component type we could even add boolean property `twice: true/false` and render confirmation field when true.

**Comment by Hyperkid123** [comment]
@miha-plesko that is actually how HTML input is defined. I would not really mess with that.

But i would be for cross field validation validator. that is something we should add.

**Comment by miha-plesko** [comment]
@Hyperkid123 thans for explanation. I don't need the cross-field validation yet so no hurry.

**Comment by rvsia** [comment]
I think with `type: password` on text-field and [crossfield validation](https://data-driven-forms.org/renderer/validators#recordlevelvalidation) you can easily create this password component in any schema.

Should we close this, @Hyperkid123  ?
