### ISSUE TITLE
Proposal - resolveProps

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#646]
**Scope**: Renderer

**Description**

I got this idea how to elevate the global props option.

```jsx
componentMapper = {
   'text-field': {
         resolveProps: (props, formOptions, meta) => {
                actionMapper: { label: ['translate', props.label] },
                helperText: value && validate && validate.length > 0 && !meta.error ? 'OK' : props.helperText
         }
   }
}
```

It could make components more customizable without touching their code. (Also, we could use the same prop as a field prop.)

What do you think, @Hyperkid123  ?

**Comment by Hyperkid123** [comment]
I assume this would have to run on each subscription change?

**Comment by rvsia** [comment]
@Hyperkid123 

Yeah, the code could be pretty simple:

```
...(resolveProps && resolveProps(props, meta, input, formOptions))
```

before the props are returned.

**Comment by Hyperkid123** [comment]
So the only question there is. Do we want to expose `formAPI` and `input` objects? This could obviously allow overriding the `change` methods. Which could potentially benefit/harm the component?

But I would expect that if somebody would be using this feature, they would probably know what they are doing so I don't see an issue with this.

To avoid overriding the props all the time in each render. Can we store these kinds of props in a ref? And update them accordingly? That is literally the only thing I would add to this. And its long overdue.

**Comment by rvsia** [comment]
This won't change anything in terms of exposing formApi/input (it would have the same effect as putting these attributes directly into a schema).

But people could use `input.value` and `getState().values` to change their components (for example change helperText if another value is filled.)

And of course, there can be additional optimization enhancements.

**Comment by Hyperkid123** [comment]
@rvsia if you promise to cache these kinds of props you have :green_circle: :wink:.

**Comment by rvsia** [comment]
The only issue I think about is mixing resolveProps and actionMapper... we would have to come up with some rules to not let people use actionMapper to call resolveProps function returning actionMapper. :smile:

**Comment by Hyperkid123** [comment]
We can forbid it or follow the general priority `schema` -> `globalSettings`
