### ISSUE TITLE
PF3 datepicker tests fail outside our timezone

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#650]
**Scope**: PF3

**Description**

Set India's timezone (or any other that has plus some minutes) and run tests for PF3 date-time-picker

`react-forms/packages/pf3-component-mapper/src/tests/form-fields/date-time-picker/time-picker.test.js`

Two tests are going to fail.

@Arun-42 Do you want to take this? I think it could be interesting entry point to tests.

**Comment by Hyperkid123** [comment]
I wonder if its possible to set the JSDOM navigator to one locale in tests :thinking:. It might be read-only property.

**Comment by Arun-42** [comment]
Yes, I want to take this issue.
