### ISSUE TITLE
Add input addons to form groups.

### ISSUE THREAD

**Issue by Hyperkid123** [data-driven-forms/react-forms#66]
- decide on schema format
  - addon before
  - addon after
- add implementation for supported components

**Comment by Hyperkid123** [comment]
cc @skatemant

**Comment by skateman** [comment]
I could imagine a schema like this:
```javascript
  fields: [{
    component: componentTypes.TEXT_FIELD,
    name: 'first-name',
    label: 'First name'
    inputAddons: {
      left: [button1, button2, button3]
      right: [button4, button5]
    }
    validate: [{
      type: validatorTypes.REQUIRED,
      message: 'First name is required'
    }, {
      type: validatorTypes.MIN_LENGTH,
      threshold: 3,
      message: 'First name must be at least 3 characters long'
    }]
  }
```

Where `buttonX` is a button specified in the DDF schema. So basically a list of `inputAddons` before and after the input field.

https://www.patternfly.org/v4/documentation/react/components/inputgroup/

**Comment by Hyperkid123** [comment]
@brumik this one is for you :wink:

**Comment by skateman** [comment]
@miq-bot assign @brumik

**Comment by brumik** [comment]
@skateman The PF3 is not prepared for multiple InputAddons in one place. The design looks sometimes broken. For example here (button and text after or double text before)

![Screenshot from 2019-09-18 14-39-26](https://user-images.githubusercontent.com/8531681/65149311-2837ce80-da22-11e9-8a7f-9643a67a8577.png)

**Comment by brumik** [comment]
Is it required to support Dropdown, Radio, Checkbox and Icon also?

**Comment by skateman** [comment]
No, for now just input.

**Comment by brumik** [comment]
I mean support in the Input addon these things: 
![Screenshot from 2019-09-18 15-28-31](https://user-images.githubusercontent.com/8531681/65152834-02fa8e80-da29-11e9-8b82-533cacc5a79f.png)

**Comment by skateman** [comment]
Ah, yes, that's probably something we want. But I'm not sure how to implement it, or that @Hyperkid123 and @rvsia would want it.

**Comment by Hyperkid123** [comment]
@brumik it is supposed tu support "everything" that you create mapping for. Design the code so its customize-able what is rendered inside the addon. Right now it can be hardcoded in the pf3 mapper because there will be need for some changes in the renderer in order to access the renderer mappers. I will take care of that once i am back from PTO. Or you can take a look and propagate the Component contex which is providing component from layoutmapper to formOptions.

@rvsia will know what i am talking about.
