### ISSUE TITLE
[manager] Combine fieldConfigs

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#739]
current behavior of FF is that it combines multiple validations to one

so validate should be stored in `fields` and it should be checked via forEach...

the same probably applies for other attributes as `isEqual` etc.

**Comment by Hyperkid123** [comment]
- [ ] validate
- [ ] isEqual

**Comment by rvsia** [comment]
_Note_: There should be also `afterSubmit`, `beforeSubmit` functions after/if we implement them.

**Comment by Hyperkid123** [comment]
We might have to change the way of how we are triggering these functions. Specifically, the revalidate form and the fields. If we want to correctly call validators on fields with the same name but different internal ID we need to store that internal ID as well. We will have to think about it a bit more. We might have to switch away from the name identifier for certain actions and use the internal id inistead.
