### ISSUE TITLE
Ability to for field to access another field's value

### ISSUE THREAD

**Issue by edhollinghurst** [data-driven-forms/react-forms#746]
Hi there, really enjoying using this library.

Just wondered whether there's a way for a field to access another field's value and receive updates whenever it changes?

I thought it would be possible with the `getState` method (see example link below). However you'll see that the received value does not get updated each time the field updates.

https://stackblitz.com/edit/zvy8e7

**Comment by rvsia** [comment]
Welcome and thank you for attaching an example.

Right now, there are two standard ways how to update the second component:

1) Set `subscription `(https://data-driven-forms.org/components/renderer#optionalprops)

```jsx
      <div style={{margin: 24}}>
        <FormRenderer
          schema={schema}
          FormTemplate={FormTemplate}
          componentMapper={componentMapper}
          onSubmit={console.log}
          subscription={{values: true}}
        />
      </div>
```

All fields will be updated when values are changed. It will hurt the performance, but in small forms it should be ok.

2) use `FormSpy` https://data-driven-forms.org/components/form-spy

You can wrap the component in `FormSpy`.

```jsx
<FormSpy subscription={{values: true}}>
   {(formState) => <CustomComponent />}
</FormSpy>
```

**Comment by edhollinghurst** [comment]
That's great - thanks very much for getting back to me so quickly.

**Comment by rvsia** [comment]
@edhollinghurst I am glad I was able to help! 👍
