### ISSUE TITLE
Typescript: Cannot import WizardContext object from module for useContext hook 

### ISSUE THREAD

**Issue by cjbos** [data-driven-forms/react-forms#786]
This is likely an issue on my end, but I'm having trouble using the WizardContext in typescript.

I have the following in my form template (Trying to implement a skip button):

```
import WizardContext from '@data-driven-forms/react-form-renderer/dist/cjs/wizard-context';
...
const { jumpToStep } = useContext(WizardContext);
```

But I get a compile error that WizardContext is a type when a value is expected.

Is there something I might be missing in my tsc compiler options?

```
"compilerOptions": {
    "jsx": "react",
    "esModuleInterop": true,
    "noEmit": true,
    "noImplicitAny": true,
    "baseUrl": "."
  }
```

**Comment by Hyperkid123** [comment]
Hello @cjbos give a second to verify. It can be an issue on our side.

**Comment by Hyperkid123** [comment]
@cjbos thanks reporting this issue, it was a bug on our side. We were exporting the context as an interface instead of React.Context.

Pr is out, once its merged new version with a fix will be released shortly: https://github.com/data-driven-forms/react-forms/pull/787.
