### ISSUE TITLE
Making condition evaluation more generic

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#802]
I'm struggling to reimplement the conditional validators described [here](https://github.com/data-driven-forms/react-forms/issues/149#issuecomment-539401224) using the validator mapper in my own codebase. It would be nice to have an `evaluateCondition` that would just give me true or false without passing any context inside:

```js
import { validatorMapper, evaluateCondition } from '@@ddf';

const decorate = fn => ({ condition, ...rest }) => {
  if (!evaluateCondition) return true;
  return fn(rest);
}

const myValidatorMapper = Object.keys(validatorMapper).reduce((obj, key) => ({
   ...obj,
   [key]: decorate(validatorMapper[key]),
}) ,{});

```

**Comment by Hyperkid123** [comment]
@skateman can you describe the specific issue you have? The [thread](https://github.com/data-driven-forms/react-forms/issues/149#issuecomment-539401224) is very outdated and has examples from v1 of the library.

Is your condition depends on different field value? What exactly `evaluateCondition` is supposed to do?

Validators have access to value, all form values and field meta. Do you think you can make it work with these?
```jsx
const validatorMapper = {
  [type]: (validatorConfigurationFromSchema) => (value, allValues, meta) => ...
}
```

**Comment by skateman** [comment]
@Hyperkid123 yes, I want the validation to depend on a value of another field. I guess I can just use `allValues`, but I'd need the condition evaluator somehow as I described in the `decorate` function.

**Comment by Hyperkid123** [comment]
@skateman are you trying to enhance existing validators or creating your own? If you are creating your own there should be no problem with adding the evaluator.
```jsx
const evaluator = () => {...} // can be defined here or inside the closure
const customValidator = (schemaConfig) = {
    // whatever is necessary with the config
  return (value, allValues) => {
    return evaluator(schemaConfig, value, allValues)
  }
}
```

If you want to enhance a current one it is exported at `/dist/{env}/validator-mapper`.

**Comment by skateman** [comment]
Yeah, I'm trying to enhance the old ones (see my example) with a decorator function that evaluates the condition passed with the decorator.
