### ISSUE TITLE
Add a search (filter) button to left nav

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#81]
What about to add a simple input which will only filter links in the menu? Until we have a proper search system, it could be a sufficient solution.

Example:

![image](https://user-images.githubusercontent.com/32869456/62684651-6a043c80-b9c1-11e9-9512-942027871183.png)

**Comment by rvsia** [comment]
@Hyperkid123

**Comment by Hyperkid123** [comment]
YES
