### ISSUE TITLE
Issues with linking on documentation website

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#811]
When opening the [`requiredValidator`](https://data-driven-forms.org/schema/required-validator#heading-requiredvalidator) example on the website, the GitHub link redirects the browser to a [404 page](https://github.com/data-driven-forms/react-forms/tree/master/packages/react-renderer-demo/src/app/examples/components/validators/required-validator.js):
![Screenshot from 2020-09-23 13-37-51](https://user-images.githubusercontent.com/649130/94007706-24abf580-fda2-11ea-945c-1b8eb35caf3c.png)

Also it would be nice to have a permalink to the code version of the example that is accessible via the `<>` button next to this.

**Comment by Hyperkid123** [comment]
@skateman I will take look a soon. Thanks for the report.
