### ISSUE TITLE
Conditionals in Field Arrays

### ISSUE THREAD

**Issue by tinkotvas** [data-driven-forms/react-forms#820]
**Scope**: Schema / FormRenderer

**Description**: Would love the ability to put up conditionals within field arrays. Currently now the condition target is an exact path, working with field arrays the field will be an array [0], [1] etc, thus making it impossible to dynamically alter the condition based on every new "row" of field array directly in the schema.

**Schema**
Short example code (disregard obvious type errors)
```js
const fieldOptions = [...fieldTypeOptions];
const fieldSchema = [...schemaFields];
const searchField = {
    component: "field-array",
    name: "FieldArr",
    fields: [
        {
            FormFieldGridProps: { md: 12 },
            component: "autocomplete-async",
            label: "Field type",
            name: "FieldType",
            options: fieldOptions,
        },
        ...Object.entries(fieldSchema).map((entry) => {
            const [key, field] = entry;
            const target = fieldOptions.find((item) => item.value == key);

            return Object.assign(field, {
                FormFieldGridProps: { md: 12 },
                condition: {
                    when: "FieldType",
                    is: target ,
                    then: { visible: true },
                },
            });
        }),
    ],
};
```

The condition will not match since FieldType in the instance will be "FieldArr[0].FieldType" and continuing on the next added field array the target will be "FieldArr[0].FieldType", making it impossible to dynamically match field array conditions based on the current instance "row"

Would be great if you could target the path based on the current index of field array, for example:
```js
condition: {
    when: (fieldIndex, rowData) => `FieldArr[${fieldIndex}].FieldType[0]`,
    is: target,
    then: { visible: true },
},
```

**Comment by Hyperkid123** [comment]
This seems legit. I assume the second argument refers to the schema definition of the fieldArray?
```jsx
when: (fieldIndex, rowData) => `FieldArr[${fieldIndex}].FieldType[0]`,
```
@tinkotvas would you up for this task? (My schedule is super busy atm.)

**Comment by rvsia** [comment]
Hello, thank you for this great suggestion!

I would change

```jsx
    when: (fieldIndex, rowData) => `FieldArr[${fieldIndex}].FieldType[0]`,
```

to something like

```jsx
    when: (field) => `FieldArr[${field.name.match(/\d+/)[0]}].FieldType[0]`,
```

`field.name` actually contains the `fieldIndex` i.e. `fieldArray[0].lastName` => `[0]` so you don't have to have a special argument for it. And it would make more sense for nested field arrays `fieldArray[0].siblings[1]` where you get both fieldIndexes via the name.

**Comment by rvsia** [comment]
I have some free time now, so I can take a look on a possible solution.

**Comment by Hyperkid123** [comment]
go for it

**Comment by Hyperkid123** [comment]
@tinkotvas do you have objections against @rvsia suggestion? Is the `rowData` argument crucial for your requirements? What kind of data is it supposed to be?

**Comment by tinkotvas** [comment]
> @tinkotvas do you have objections against @rvsia suggestion? Is the `rowData` argument crucial for your requirements? What kind of data is it supposed to be?

It's not crucial, my intention was only to give a example on a usecase, if this would be the best solution with the current code base it would work.

I haven't checked the current source for this, but I believe having access to the row data (or internal used values like the index) would be a preferable solution to matching strings. But I guess it depends on if it's possible with the code as it is right now without any significant performance losses.

But yes, the suggestion from @rvsia would work great.

**Comment by Hyperkid123** [comment]
@tinkotvas the "problem" with passing just the index are nested fields really. As @rvsia has pointed out, the name gives you all the information about the position of the field you would need, whereas the index would only give you the position in the current "layer" which might not be enough. So the "name" should be definitely passed.

@rvsia I would suggest adding the second argument which would give additional metadata to the condition definition. There we can have the index, field name, and field array name as separate values. Using the index directly is definitely faster than string matching.

**Comment by rvsia** [comment]
@Hyperkid123 I think that would be an unnecessary redundancy - fieldArray name and fieldName is known directly from the schema, so there is no need to pass them. And to pass index it would mean to change `renderForm` across all fieldArray components and it would break simply with nesting.

**Comment by Hyperkid123** [comment]
> And to pass index it would mean to change renderForm across all fieldArray components

I see. I would not want that. The name will have to be sufficient.

**Comment by Hyperkid123** [comment]
@tinkotvas new version with the feature should be released in a couple of minutes. I will keep this issue open until your ack that it is working as intended.

**Comment by tinkotvas** [comment]
Working as intended!
