### ISSUE TITLE
[CustomValidator] Custom warning instead of custom error

### ISSUE THREAD

**Issue by alexandernst** [data-driven-forms/react-forms#835]
**Scope**: CustomValidator functionality

**Description**

I'm working with forms that require showing "alerts/warnings" on some fields after validating them.
For example, after entering a text in a field, the validation of that field should be triggered and if the value of the field matches a previously fetched array of values, the field should show a warning message of some sort (eg. "the value already exists").

The thing is that the message shouldn't be treated as a validation error, meaning that the form should still be submittable (if there are no other fields with an actual error).

If I have understood the docs correctly, there is no way for achieving this currently, aka, Validators can trigger "error" or "not error", but they can't trigger "kind of an error, but not error". Is that correct?

If that is not correct, how can I handle a case like the one I just described?

**Schema**

N/A

**Comment by alexandernst** [comment]
Hi @Hyperkid123 !

I really wasn't expecting a reply so sooner, so thank you!

Indeed, I was thinking that a custom component might the the "plan B", but I really don't like the idea of overriding and hacking into components just for this one thing. 

Replying to your second comment: your proposal sounds like a very elegant way for achieving this feature, bonus points for not breaking any current APIs. I really like it!

**Comment by rvsia** [comment]
@alexandernst Thank you for your suggestion! And thanks @Hyperkid123 for a more detailed proposal. I can take a look tomorrow - I have several ideas in my head how to implement this feature. :thinking: 

But feel free to open a PR yourself if you want to! :+1:

**Comment by Hyperkid123** [comment]
@alexandernst the renderer now has soft validation. We will need to update the mappers accordingly. Which component mapper are you using?

**Comment by alexandernst** [comment]
Actually I'm working on a custom bootstrap 4 (WIP, pre-alpha) mapper. I'll share it if I get it to work decently.

**Comment by Hyperkid123** [comment]
@alexandernst alright. The updated docs should be up in a bit.

**Comment by alexandernst** [comment]
Thank you all for the extremely fast replies and patches!

**Comment by rvsia** [comment]
@alexandernst The docs are here https://data-driven-forms.org/schema/validator-warnings (if you can't see it, try to force refresh)
