### ISSUE TITLE
Demos on the website are failing to build

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#865]
![Screenshot from 2020-10-28 14-44-58](https://user-images.githubusercontent.com/649130/97444201-2aaa6e80-192c-11eb-9515-6a043d5bb831.png)

**Comment by Hyperkid123** [comment]
@skateman does it happen for all mappers?

**Comment by skateman** [comment]
It seems like only PF3 :thinking:

**Comment by Hyperkid123** [comment]
@skateman I think I have all of them. The attached PR fixes the issue.
