### ISSUE TITLE
How to handle phone number type inputs?

### ISSUE THREAD

**Issue by jinxac** [data-driven-forms/react-forms#885]
**Scope**: MUI Wrapper

**Description**

Hi, I was looking to integrate a phone number into the forms. Is there any way I can use a custom component for the same? The custom component I am talking about here is https://github.com/bl00mber/react-phone-input-2.

TIA

**Schema**

<If it's possible, please provide a schema which reproduces the issue>

**Comment by rvsia** [comment]
Hello, yeah, you can follow this [guide](https://data-driven-forms.org/mappers/custom-mapper#creatingforminputcomponents):

```jsx
import useFielApi from '@data-driven-forms/react-form-renderer/dist/cjs/use-field-api';

const PhoneNumber = (props) => {
  const {input} = useFielApi(props);

  return (<PhoneInput
    country={'us'}
    {...input}
  />)
}
```

demo: https://stackblitz.com/edit/g5ghky?file=index.js

**Comment by jinxac** [comment]
Thank you so much for the prompt reply. This works super nice. Just one last question how do I adjust styles/validations for this? I am passing following in the schema but it is not working:-


```
      {
        name: "phoneNumber",
        label: "Phone Number",
        component: "phone-number",
        FormFieldGridProps: {xs: 6},
        isRequired: true,
        placeholder: "",
        validate: [
          {
            type: validatorTypes.REQUIRED
          }
        ],
        initialValue: data.phoneNumber
      },
```

**Comment by rvsia** [comment]
Validation works, it just does not show errors. You need to wrap the component inside a `FormField` component that enables all these features, you can take a look here how it's implemented in MUI: https://github.com/data-driven-forms/react-forms/blob/master/packages/mui-component-mapper/src/files/switch.js#L10

**Comment by jinxac** [comment]
Thanks a ton, will go over it once.

**Comment by rvsia** [comment]
No problem! I will close this for now - feel free to re-open if you need any help!
