### ISSUE TITLE
Submit enabled even though form is pristine (MUI)

### ISSUE THREAD

**Issue by jeffmcaffer** [data-driven-forms/react-forms#887]
**Scope**: 

Using the MUI component mapper to render a simple form (with or without `initalValue` values) the Submit button is enabled. Seems like the form should start out `pristine` and that Submit should be disabled until there is something to submit. 
The standard form template has the following prop on the Submit button
```
        disabled={submitting || validating || disableSubmit}
```

Could/should it also have a `|| pristine` clause?

I realize that I can do my own template. I'm wondering if I've missed another way to do this or there are reasons that it should be enabled.

**Comment by rvsia** [comment]
Hello,

yes, you can select any state to disable the submit: [see here](data-driven-forms.org /components/form-template#defaultformtemplates) via `disableSubmit` prop.

`FormTemplate={(props) => <FormTemplate {props} disableSubmit={[“pristine”]} ... />} `

**Comment by jeffmcaffer** [comment]
Perfect. Thanks for the fast response (and all the work on the form system)
