### ISSUE TITLE
How to manage dynamic list with custom objects inside select type input?

### ISSUE THREAD

**Issue by jinxac** [data-driven-forms/react-forms#888]
**Scope**: Form Renderer

**Description**

Hi,

I have a scenario in which I need to add a dynamic row inside my form by pressing an add button.

This add button on the press shows a list of options which is available. Once any of the options are selected the dynamic row is added.

The dynamically added row consists of 2 fields, one is a label which is the selected option and the other is a select input type(a percentage for the selected option). 

Now, there are few checks here which are needed here:-

1. The combined percentage for all rows should be less than or equal to 100.
2. On pressing the add button the list should not show the options which are already added earlier.

I was exploring https://data-driven-forms.org/components/field-array#heading-dynamicfields and there are few places where I got stuck:-

1. How to show a custom list on pressing the add button?
2. How to set the label and a default percentage for the selected text?

I am attaching screenshots for reference. 

<img width="1100" alt="Screenshot 2020-11-16 at 12 35 51 PM" src="https://user-images.githubusercontent.com/15068096/99223203-127e8e80-280a-11eb-8d4b-9fa6a30de9d9.png">
<img width="960" alt="Screenshot 2020-11-16 at 12 36 01 PM" src="https://user-images.githubusercontent.com/15068096/99223212-16aaac00-280a-11eb-9f76-3e5179f1e5ec.png">

**Comment by Hyperkid123** [comment]
@jinxac I think I understand your use case.

I don't think you will be able to do that with our implementation of the field array component. The field array is there to add multiple entries of the same data structure and return an array of values (plain or objects) under one key.

Theoretically, you have a field array of integer values where the label is dynamically picked. And then using some custom or global validation function.

But personally, I think it would be quicker to make a custom component. The field array does not provide the correct data format, dynamic labels are not possible and the add button will only add items with predefined configuration. Also, the validation is not suited for this kind of use case.

If you need any assistance with creating such a component, let us know, we will gladly give you a hand. I think this would be a nice example for the docs on how to create more complex custom components.

**Comment by jinxac** [comment]
@Hyperkid123 thank you for your reply. I was thinking above the design and I was thinking if I can modify UI a bit it will make more sense from code as well as the user experience.

I have created a code snippet here at https://stackblitz.com/edit/g5ghky-h6vuya where instead of showing a dynamic list on pressing add I just add a row with select options to choose form. 

This greatly simplifies the UI perspective of it.

Now, coming to the functionality. I need to maintain a check where the combined percentage of all the rows should not be more than 100%. In order to maintain this following scenario comes up:-

1. What if the user adds a row and the combined percentage goes up above 100(This can be validated in add on click easily)
2. What if the user edits an already existing row and the value goes above 100(This case is really complicated and I don't think it is possible to check this on the onChange level, because I won't know which row to keep and how/what to inform the user).
3. The list entry which is already present should not be allowed to be added again. (This again becomes tricky and needs to modify schema options on the fly, which will make things more complicated).


Based on the above I am thinking, I will just ahead and add the validation check in the `onSubmit` function which will alert the user in case any of the above occurs and ask him/her to rectify the same.

**Comment by Hyperkid123** [comment]
@jinxac sounds good.
