### ISSUE TITLE
PF3: datepicker broken in the demo

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#890]
![Screenshot from 2020-11-18 13-46-16](https://user-images.githubusercontent.com/649130/99532382-7d63cd00-29a4-11eb-8a7b-2bbdd59f0ac5.png)

I'm trying to figure out if we have a bug or it's a global problem and I bumped into this when I try to pick a date.

**Comment by Hyperkid123** [comment]
Looks like stackblitz is for some reason installing react@17 even though we have it locked at 16.4.0. Don't know if that something we can fix on the demo page.

**Comment by rvsia** [comment]
@Hyperkid123 StackBlitz does what Stackblitz wants to do. I can still see `react 16.14.0` and it works fine. :man_shrugging:

**Comment by Hyperkid123** [comment]
Yeah it works until you open the dropdown then it crashes and the error with react-dom 17 pops up.
