### ISSUE TITLE
Conditional showing of fields not working properly with field-arrays

### ISSUE THREAD

**Issue by jinxac** [data-driven-forms/react-forms#897]
**Scope**: Form renderer

**Description**

Hi, I wanted to show fields based on a checkbox selection. It works fine with normal fields however field array is giving me issues. Attaching the link to the schema. In this, I want to show fields on choosing a permanent address is the same as the default address.

I found a similar [issue](https://github.com/data-driven-forms/react-forms/issues/820) while going over the list of issues. It says that it is fixed but for me, on the latest build it is not working

**Schema**

https://codesandbox.io/s/cool-bogdan-1gwk9?file=/package.json

<If it's possible, please provide a schema which reproduces the issue>

**Comment by rvsia** [comment]
Hello,

You can check https://github.com/data-driven-forms/react-forms/issues/820 for a solution. 

Basically, you just need to use a function in `when` (see [here](https://data-driven-forms.org/schema/condition-schema#when)) to generate a proper name with a index for the current field array field. This function receives the field as the first argument, so you can use it.

In your case the when function would like this:

```jsx
when: (field) => field.name.replace(/\..*$/, 'correspondenceAddressSameAsPermanentAddress')
// replaces the last part of the name with the name of the field you want to check
// 'nice_people[0].addressLine1' => 'nice_people[0].correspondenceAddressSameAsPermanentAddress'
```

**Comment by jinxac** [comment]
thank you so much for the reply. This works fine.
