### ISSUE TITLE
How to check a condition based on value of input?

### ISSUE THREAD

**Issue by jinxac** [data-driven-forms/react-forms#899]
**Scope**: Form Renderer

**Description**

Hi, I have to show a few fields based on if the age entered is <18 years or not. Is there a way in which I can implement this? TIA

**Schema**

<If it's possible, please provide a schema which reproduces the issue>

**Comment by Hyperkid123** [comment]
@jinxac we have a quite nice condition engine to show/hide fieds. Check this section of docs: https://data-driven-forms.org/schema/condition-schema

If you want to apply the same condition on multiple fields, you can wrap them in sub form component and apply the condition on it.

**Comment by jinxac** [comment]
I had checked the fields but it just checks for a boolean value in the `is` field. My requirement is that I have the date of the birth input date field. From this, I need to see if the year is less than 18 then I need to show a few more fields. How and where can I add such validations?

**Comment by rvsia** [comment]
I think we could implement more math operators/custom function. I can take a look today.

**Comment by Hyperkid123** [comment]
Right we don't have those, but technically you can achieve that with the regexp condition handler.

**Comment by Hyperkid123** [comment]
@rvsia if you have a bit of time, go for it. This one is missing. I would also consider enabling a custom function for the `is` config. It would be handy in cases like this.

**Comment by rvsia** [comment]
Otherwise, until it’s added to the library, you could do a work-around: use an invisible field wrapped in FormSpy, that checks the date of the birth, compute if it’s younger and via formOptions sets a form value to true or false. And then, you can check the computed value instead of the date.

**Comment by jinxac** [comment]
@rvsia thank you for your reply. The documentation does not mention a lot about FormSpy. Can you please help me out here?

**Comment by Hyperkid123** [comment]
Form spy is just a wrapper about react final from spy the link should be in the docs (https://final-form.org/docs/react-final-form/api/FormSpy).

Basically, it's an observer of the form state and through it, you can access the form state (values, errors, etc.).

**Comment by rvsia** [comment]
I can provide an example of this custom component:

```jsx
const AgeWatcher = ({ values }) => {
  const { change } = useFormApi();

  useEffect(() => {
    if (isAdult(values.dateOfBirth)) {
      change('isAdult', true); // set isAdult value to true, don't forget to remove in the submit function
    } else {
      change('isAdult', false);
    }
  }, [values.dateOfBirth]);

  return null; // set also hideField: true in the schema to not mess the grid system
};

// FormSpy ensures that the component will be rendered on each formState 
export default () => <FormSpy subscription={{values: true}}>{(props) => <AgeWatcher {...props} />}</FormSpy>;
```

**Comment by jinxac** [comment]
Thank you so much for the example, I tried implementing me but I am not getting the values. It just gives the component and name of field as props. 


Here is the code location where I am trying https://stackblitz.com/edit/g5ghky-mctw1z?file=schema.js

**Comment by rvsia** [comment]
@jinxac 

You have to use the wrapped component in your mapper. (`export default` was an example of component living in a seperate folder)

```jsx
import FormSpy from "@data-driven-forms/react-form-renderer/dist/cjs/form-spy";

const WrapperAgeWatcher = () => (
  <FormSpy subscription={{ values: true }}>
    {(props) => {
      console.log("parent props...", props);
      return <AgeWatcher {...props} />;
    }}
  </FormSpy>
);

const customComponentMapper = {
  ...componentMapper,
  "new-component": WrapperAgeWatcher
};
```

**Comment by jinxac** [comment]
yes, I realized that as I was debugging, hence deleted my earlier comment. This works fine as expected. Thank you so much

**Comment by jinxac** [comment]
@Hyperkid123 @rvsia I was using the above mentioned inside a FieldArray and I am getting an error " FormSpy must be used inside of a <Form> component". Any idea on how to resolve this?

**Comment by Hyperkid123** [comment]
@jinxac you are probably mixing `cjs/esm` imports.

What are your import paths of form renderer and the formSpy?

**Comment by jinxac** [comment]
Yes, Thank you that was the issue. One last thing. I have a field array with add a row functionality. 

1. Inside by FormSpy how will I know which index I need to use to change?
2. Inside my FieldArray schema how I do specify the name of this field?

TIA

**Comment by jinxac** [comment]
Looks like it works fine after I run a loop inside my FormSpy component and check for each item individually. This works fine but looks a like hack.

**Comment by rvsia** [comment]
@jinxac A new version of DDF was released. You can now use `is` function (check [here](https://data-driven-forms.org/schema/is#customfunction)), so you don't need to use the FormSpy component anymore.

However, if you use the WrapperAgeWatcher in each FieldArray group, then it should receive the `name` with the correct index as a prop.

```jsx
const WrapperAgeWatcher = ({ name }) => (
  // name = nicePeople[12].ageWatcher or something like this
  <FormSpy subscription={{ values: true }}>
    {(props) => {
      console.log("parent props...", props);
      return <AgeWatcher {...props} />;
    }}
  </FormSpy>
);
```
