### ISSUE TITLE
Cannot call setIn() with undefined key

### ISSUE THREAD

**Issue by jinxac** [data-driven-forms/react-forms#910]
**Scope** - Form Renderer

**Description**

I was trying to include select with autocomplete component using material autocomplete. However, after including the above in the project I started getting the error `Cannot call setIn() with undefined key` on input change. Can someone please help me out here?

**Schema**

Attaching the schema for the same. https://stackblitz.com/edit/g5ghky-78chnl?file=index.js

**Comment by jinxac** [comment]
This works fine if the autocomplete component is used as a stand alone. Using inside form renderer gives me above error.

**Comment by jinxac** [comment]
Here is a detailed stack trace of the above issue:


```

Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead.
in p (created by ForwardRef(FormHelperText))
in ForwardRef(FormHelperText) (created by WithStyles(ForwardRef(FormHelperText)))
in WithStyles(ForwardRef(FormHelperText)) (created by ForwardRef(TextField))
in div (created by ForwardRef(FormControl))
in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
in WithStyles(ForwardRef(FormControl)) (created by ForwardRef(TextField))
in ForwardRef(TextField) (created by WithStyles(ForwardRef(TextField)))
in WithStyles(ForwardRef(TextField)) (created by TextField)
in div (created by ForwardRef(Grid))
in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
in WithStyles(ForwardRef(Grid)) (created by FormFieldGrid)
in FormFieldGrid (created by TextField)
in TextField (created by ForwardRef(Autocomplete))
in div (created by ForwardRef(Autocomplete))
in ForwardRef(Autocomplete) (created by WithStyles(ForwardRef(Autocomplete)))
in WithStyles(ForwardRef(Autocomplete)) (created by CountrySelect)
in CountrySelect (created by SingleField)
in FormFieldHideWrapper (created by SingleField)
in FormConditionWrapper (created by SingleField)
in SingleField (created by ReactFinalForm)
in div (created by ForwardRef(Grid))
in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
in WithStyles(ForwardRef(Grid)) (created by Form)
in form (created by Form)
in div (created by ForwardRef(Grid))
in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
in WithStyles(ForwardRef(Grid)) (created by Form)
in Form (created by FormTemplate)
in FormTemplate (created by MuiFormTemplate)
in MuiFormTemplate (created by ReactFinalForm)
in ReactFinalForm (created by FormRenderer)
in FormRenderer (created by App)
in div (created by App)
in App
```

**Comment by Hyperkid123** [comment]
Thanks for the info, I will what is going on.

**Comment by Hyperkid123** [comment]
The first issue I have found is that you are using a DDF text field as the autocomplete `renderInput`. You should not do that. The component is not supposed to be connected to the form state (which DDF text field us by default). It was crashing on me when I closed the autocomplete component even though it was not using the DDF API.

**Comment by Hyperkid123** [comment]
@jinxac and that seem to be the issue. Look at this example, after selecting an option and pressing the submit, the correct value is shown in the browser console: https://stackblitz.com/edit/g5ghky-x637g8?file=index.js

**The example is not controlled and does not use the form state value.**

**Comment by jinxac** [comment]
@Hyperkid123 oh shucks, I did not see the import. Thank you so much.
