### ISSUE TITLE
Soften node version restriction

### ISSUE THREAD

**Issue by Hyperkid123** [data-driven-forms/react-forms#929]
Firebase should now support node v10+ not only 8 and 10.

If that is the case, we can soften the restriction from v10 to >=10 & <=14

**Comment by rvsia** [comment]
@Hyperkid123 Did an investigation about this:

1. Firebase tools seem to not allow using more complex node engines set.

```⚠  Your requested "node" version ">=10 <15" doesn't match your global version "10"```

2. The new version breaks `firebase serve` - there are now emulators but it throws an error to me.

```⚠  TypeError: Cannot set property GrpcClient of #<Object> which has only a getter```

**Comment by Hyperkid123** [comment]
@rvsia 
> Firebase tools seem to not allow using more complex node engines set.

Well if the npm definition `{ "engines" : { "node" : ">=0.10.3 <0.12" } }` does not work for some reason. We can set it to 14. Using the LTS version should be good enough. That is a bummer.

>The new version breaks firebase serve - there are now emulators but it throws an error to me.

You might have to update the firebase-tools and other firebase utils.

**Comment by rvsia** [comment]
@Hyperkid123 

1. Yeah. Maybe we can ignore the warning, it seems that it doesn't block anything.

2. Yep, I have updated the whole firebase suite.

**Comment by Hyperkid123** [comment]
@rvsia does the firebase error occur locally on actually on firebase?

**Comment by rvsia** [comment]
Ohhhhh it was cause by using a global package instead of local. :facepalm: 

But instead of it I got a new one:

```
 [ error ] ./src/pages/_app.js
>  Module not found: Can't resolve '@docs/components/layout' in '/home/rvsianskz/driven-forms/react-forms/packages/react-renderer-demo/src/pages'
>  (node:81751) UnhandledPromiseRejectionWarning: Error: Cannot find module '/home/rvsianskz/driven-forms/react-forms/packages/react-renderer-demo/dist/server/static/development/pages/_document'
```

**Comment by Hyperkid123** [comment]
I would suggest clearing all the builds and modules and trying it again. Locally.

**Comment by rvsia** [comment]
I am still not able to get it work (after removal of the aliases from the code, it doesn't work at all anyways... :D), until then I have updated all other dependencies to make the future transitions as simple as possible: https://github.com/data-driven-forms/react-forms/pull/930

**Comment by Hyperkid123** [comment]
Oh god. I am tempted to just switch to a different hosting.
