### ISSUE TITLE
[v3] Wrong testcoverage

### ISSUE THREAD

**Issue by rvsia** [data-driven-forms/react-forms#932]
**Scope**: v3

**Description**

v3 shows wrong coverage for wizard components. This alone decreases the coverage about 10%

**Comment by rvsia** [comment]
Packages has wrongly set index.js so they took components from build (https://github.com/data-driven-forms/react-forms/issues/932)

And for some reason codecoverage is not able now to follow `common` package, maybe bacause it also takes the built version...

**Comment by Hyperkid123** [comment]
@rvsia thats because the common packages is now actually a package. So the test files are using the source code, but the build bundle which then causes the test coverage to be reduced. We have to move the test files to the common package a run it from there.
