### ISSUE TITLE
Carbon: subform default TitleElement should be larger

### ISSUE THREAD

**Issue by skateman** [data-driven-forms/react-forms#946]
Apparently the subform titles (labels?) are not large enough to distinguish them from field titles. As far as I see right now it's just rendering a [`<h5>`](https://github.com/data-driven-forms/react-forms/blob/dd4ca016787011e3b707fbe158a2ad63047bd6be/packages/react-renderer-demo/src/doc-components/examples-texts/carbon/sub-form.md#L5) but we might need a `h4` or a `h3`.

@kavyanekkalapu can you please tell which one to use?

**Comment by rvsia** [comment]
It's already fully customizable https://data-driven-forms.org/mappers/sub-form?mapper=carbon#props see TitleElement

**Comment by skateman** [comment]
I know, I'm talking about its default value

**Comment by rvsia** [comment]
Yeah, I understand. If UX confirms we need a different element, please go and change the default prop. It's nothing truly breaking.

**Comment by kavyanekkalapu** [comment]
@rvsia @skateman h3 looks better. thanks @skateman for screenshot.
